### ISSUE TITLE
[Feature] Website UI Overhaul

### ISSUE THREAD

**Issue by itsmeboy0** [ScoopInstaller/Scoop#4827] opened 2022-03-21 05:11 UTC
#### Is your feature request related to a problem? Please describe.
https://scoop.sh/ looks too old for its time. It also looks like it hasn't been updated for a long time (outdated links and information). I think it needs an overhaul.

#### Describe the solution you'd like
Have a look at https://scoop-docs.vercel.app/ (https://github.com/kidonng/scoop-docs). I think you already know about this. Why not merge that to the official website?

#### Describe alternatives you've considered
Remake the website UI from scratch.

**Comment by rashil2000** [comment] 2022-03-21 06:53
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/4627

**Closed by rashil2000** 2022-03-21 06:53 UTC
Labels: enhancement

**Comment by itsmeboy0** [comment] 2022-03-21 06:56
That issue is more of a web search UI. I'm talking about a homepage and a documentation website in this issuse.

**Comment by rashil2000** [comment] 2022-03-21 07:03
That issue includes discussion about a homepage in the same website
