### ISSUE TITLE
[Bug] scoop install . bricks scoop and all installed programs

### ISSUE THREAD

**Issue by optimizasean** [ScoopInstaller/Scoop#4812] opened 2022-03-15 03:17 UTC
`scoop install .` breaks scoop - it uninstalls scoop partially (enough not to be easily fixable if at all) and everything else (only the shims I think?).

This command should be checked for and ignored, definitely not something that should happen by default as I just undid an hour of work setting something up in seconds.

**Comment by rashil2000** [comment] 2022-03-15 04:35
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/2370

**Closed** 2022-03-15 04:35 UTC
Labels: bug
