### ISSUE TITLE
[Bug] Launched shims leave console windows if not attached to existing console session (annoying for GUI apps when Ctrl+TAB)

### ISSUE THREAD

**Issue by gavenkoa** [ScoopInstaller/Scoop#5049] opened 2022-07-18 13:54 UTC
If I run a GUI app (sysinternals / notepad++) from GUI environment (so a shim cannot attach to an existing console), like

* Win+R
* Start menu
 
they are opened with annoying console window. This **doubles the list length for windows you see in Ctrl+TAB**.

When you build a Windows app you define if it will be console or GUI.

As some programs are CLI oriented I understand the need for a shim to be a *console app*. And seems scoop project avoids to maintain two builds of shims (GUI and console ones).

The console should be hidden for GUI applications. Package authors should specify if the app is GUI and Scoop should use different shim implementation.

As a workaroud I put `scoop/app/<name>/current` to `PATH` before `scoop/shims`: basically hiding shims. I need to do this for every interesting package...

**Comment by rashil2000** [comment] 2022-07-18 13:58
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/1606

**Closed by rashil2000** 2022-07-18 13:58 UTC
Labels: bug
