### ISSUE TITLE
[Feature] Allow other app update/install/whatever actions to proceed after one fails

### ISSUE THREAD

**Issue by studoot** [ScoopInstaller/Scoop#5063] opened 2022-07-25 12:35 UTC
#### Is your feature request related to a problem? Please describe.
I'm trying to `scoop update --all`, which shows this list of apps to be updated:

```
gnuplot: 5.4.3 -> 5.4.4
go: 1.18.3 -> 1.18.4
graphviz: 4.0.0 -> 5.0.0
imagemagick: 7.1.0-39 -> 7.1.0-44
just: 1.2.0 -> 1.3.0
mercurial: 6.1.4 -> 6.2
rustup: 1.24.3 -> 1.25.1
watchexec: 1.20.3 -> 1.20.4
```

Unfortunately, gnuplot's download server (`sourceforge.net`) is down right now, and `scoop update` throws an exception:

```
Updating 8 outdated apps:
Updating 'gnuplot' (5.4.3 -> 5.4.4)
Downloading new version
A connection attempt failed because the connected party did not properly respond after a 
period of time, or established connection failed because connected host has failed to respond   
204.68.111.105:443
At C:\Users\u404261\scoop\apps\scoop\current\lib\install.ps1:107 char:9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], SocketException
    + FullyQualifiedErrorId : A connection attempt failed because the connected party did not   
   properly respond after a period of time, or established connection failed because connecte   
  d host has failed to respond 204.68.111.105:443
  ```

This causes the entire update workflow to terminate.

#### Describe the solution you'd like
Provide a config setting and/or command-line option to allow me to (in effect) say "ignore failed updates", which would report that scoop couldn't update gunplot, but then went on to update (or try to update) the other 7 apps.

Preferably, scoop would also re-report failed updates when all work has been completed.

This sort of setting should also be used for *any* sub-command that can accept multiple `<app>` parameters, whether expressed explicitly or implicitly using `--all` or `'*'` for the `<app>` command-line parameter.

#### Describe alternatives you've considered
N/A

**Comment by rashil2000** [comment] 2022-07-25 12:54
Duplicate of #4135

**Closed by rashil2000** 2022-07-25 12:54 UTC
Labels: enhancement
