### ISSUE TITLE
[Bug] Bucket isn't correctly recognized when installing old versions of a package

### ISSUE THREAD

**Issue by ppvnf** [ScoopInstaller/Scoop#5320] opened 2023-01-05 23:10 UTC
## Bug Report

1 - Install an old version of some package (example from extras bucket: `scoop install firefox@108.0.1`)

2 - run `scoop list`

![Captura de tela 2023-01-05 200401](https://user-images.githubusercontent.com/73800734/210896862-7d35066a-412c-4179-8d5b-9ba7c1606ada.png)

#### Current Behavior

Source is reported as `<auto-generated>`

#### Expected Behavior

Source should be reported as `extras`

#### Related issue:

https://github.com/ScoopInstaller/Scoop/issues/3045

**Comment by HUMORCE** [comment] 2023-01-05 23:30
This is expected behavior for the current design.

Duplicate of #3045

**Closed by HUMORCE** 2023-01-05 23:30 UTC
Labels: bug

**Comment by ppvnf** [comment] 2023-01-06 09:40
Is there any workaround?

**Comment by HUMORCE** [comment] 2023-01-06 12:46
> I wish there was an easier way

What is your purpose, updating older version of apps? or what

**Comment by ppvnf** [comment] 2023-01-06 12:51
> > I wish there was an easier way
> 
> What is your purpose, updating older version of apps? or what

For example, testing if scoop successfully updates a package from an old to a new version

**Comment by HUMORCE** [comment] 2023-01-06 13:21
app.json
```
version: 1.0,
pre_install: "INFO 'App: version 1.0 installed.'",
post_install: "start-process app.exe"
pre_uninstall: "stop-process app.exe"
```

app.json >LATEST
```
version: 1.1,
pre_install: "INFO 'App: version 1.1 installed.'",
post_install: "start-process app.exe"
```

```
> scoop install app           # when 1.0 is latest version.
INFO App: version 1.0 installed.
> scoop uninstall app
'app' was uninstalled.
```

```
> scoop install app@1.0
INFO App: version 1.1 installed.
> scoop uninstall app
app.exe still running.
```

`app@1.0 <auto-generated>` is not exactly equal to manifest of app v1.0.
