### ISSUE TITLE
.ps1 shims breaking applications that call program via start-process

### ISSUE THREAD

**Issue by JustinGrote** [ScoopInstaller/Scoop#3749] opened 2019-11-15 21:57 UTC
Simple one:
scoop install git
Invoke-Git

`Exception calling "Start" with "0" argument(s): "The specified executable is not a valid application for this OS platform."`

This happens because the program looks for "git" and "git.ps1" is returned as the first result, which is not an exe.

Is there a way to make git.exe the first in the path search? maybe two paths for shims with the .ps1 in a lower order?

Is there a setting to disable .ps1 shim creation? Why do they exist anyways if the .exe shims are created?

**Comment by mihai-unity** [comment] 2020-02-26 14:33
Yeah, and:

```ps1
PS C:\> (Get-Command "python").Path
C:\Users\mihai\scoop\shims\python.ps1
``` 

will break any subsequent `Start-Process` relaying on that information:
```
Start-Process : This command cannot be run due to the error: %1 is not a valid Win32 application.
```

**Comment by mihai-unity** [comment] 2020-02-26 14:41
FWIW, I'm going to do this:

```ps1
$pythonPath = (Get-Command "python").Path
if ((Get-Item $pythonPath).Extension -eq ".ps1") {
    $pythonPath = iex "$pythonPath -c `"import sys; print(sys.executable)`""
}
```

**Comment by JustinGrote** [comment] 2020-03-17 03:34
@r15ch13 would you accept a pull request to allow a manifest option to suppress the .ps1 generation for apps where this is a continual problem?

**Comment by imgx64** [comment] 2020-08-16 08:20
Another issue caused by .ps1 shims: mklement0/Native#3

**Comment by rashil2000** [comment] 2021-12-02 18:15
Merged in develop branch - #4543

**Closed by rashil2000** 2021-12-02 18:15 UTC
