### ISSUE TITLE
[Bug] Trying to install a package after installing scoop with custom directories does not work

### ISSUE THREAD

**Issue by e-sushi** [ScoopInstaller/Scoop#4976] opened 2022-06-09 23:17 UTC
#### Current Behavior

I just installed scoop on a fresh install of Windows 10 to custom directories using this command:
```
.\install.ps1 -RunAsAdmin -ScoopDir 'H:/software!/tools/scoop' -ScoopGlobalDir 'H:/software!/apps' -NoProxy
```
Then I tried running `scoop install git` and was met with:
```
PS H:\> scoop install git
Get-ChildItem : Cannot find path 'C:\Users\sushi\scoop\buckets' because it does not exist.
At H:\software!\tools\scoop\apps\scoop\current\lib\buckets.ps1:61 char:21
+     $bucketNames = (Get-ChildItem -Path $bucketsdir -Directory).Name
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\sushi\scoop\buckets:String) [Get-ChildItem], It
   emNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Couldn't find manifest for 'git'.
```
It seems like its still looking in my users folder for the buckets, but I'm not sure why.

#### Expected Behavior

It finds the buckets on my H: drive that I installed scoop to and installs git.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:**
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682
pretty

**Additional software:** ConEmu

#### Scoop Configuration
```
{
    "rootPath":  "H:/software!/tools/scoop",
    "globalPath":  "H:/software!/apps",
    "lastUpdate":  "2022-06-09T19:04:17.8367189-04:00"
}
```

**Comment by e-sushi** [comment] 2022-06-10 00:39
scoop doesn't seem to set the environment variables and the .config is located in my Users folder on my C drive. Do I have to place it somewhere else if I didn't install to the default location? 

Temporary solution is running `$env:scoop = "H:/software!/tools/scoop"`.

**Comment by rashil2000** [comment] 2022-06-10 05:55
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/4918

**Closed by rashil2000** 2022-06-10 05:55 UTC
Labels: bug
