### ISSUE TITLE
New option "ignore-errors" for command update *

### ISSUE THREAD

**Issue by bfharreguy** [ScoopInstaller/Scoop#4854] opened 2022-04-02 02:42 UTC
#### Is your feature request related to a problem? Please describe.
When runing the command scoop update * i have a Simple error like 
"cannot update becouse its running"
"error cannot search 404"
becouse of that , cannot update all packages, stops right there

#### Describe the solution you'd like
a opcion in the command "scoop update *"  like ignore errors, only that, and all packages will be update, ignoring the errors, or packages cannot update

#### Describe alternatives you've considered
Within igniring this errors, A scheduled task can be carried out to be able to carry out the updates in a certain period, and if not all the packages can be updated, they will be achieved at another time

**Comment by rashil2000** [comment] 2022-04-02 10:11
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/4135

**Closed by rashil2000** 2022-04-02 10:11 UTC
Labels: enhancement
