### ISSUE TITLE
`scoop status` does not detect network failure

### ISSUE THREAD

**Issue by d2s** [ScoopInstaller/Scoop#3363] opened 2019-04-23 17:30 UTC
When running `scoop status` command without online connection,
Scoop prints out message saying that `Scoop is up to date. Everything is ok!`.
(even while the previous line says that connection failed).

```
> scoop status
fatal: unable to access 'https://github.com/lukesampson/scoop/': Could not resolve host: github.com
Scoop is up to date.
Everything is ok!
```

Expected output would have been to parse the `Could not resolve host` line,
and adjust following lines (about `Everything is ok!`) accordingly.

After the network connection was recovered (by plugging the cable to the wall...),
everything else was back to normal.

```
> scoop status
Scoop is up to date.
Everything is ok!
```

**Comment by Ash258** [comment] 2019-04-23 17:52
Duplicate of #3188

**Closed** 2022-01-07 08:42 UTC
