### ISSUE TITLE
[Feature] Shortcuts to packages on the desktop !

### ISSUE THREAD

**Issue by fr3nchalp4a** [ScoopInstaller/Scoop#5311] opened 2022-12-29 08:55 UTC
#### Is your feature request related to a problem? Please describe.
Since Windows 10/11, accessing principal apps on the desktop is much simpler than getting them in the start menu. But when installing packages, Scoop places the shortcut only in the start menu folder. It's actually not practical to grab the shortcuts we want in this folder then paste them in the Desktop.

#### Describe the solution you'd like   
2 ways :   
- A flag on the `install` command (`sudo scoop install firefox -d` for example, will just add the shortcut if the package is already installed)
- A second command : `sudo scoop desktop add firefox` (Add the desktop shortcut of  `firefox`)

#### Describe alternatives you've considered
Actually a duplicate of [issue 4212](https://github.com/ScoopInstaller/Scoop/issues/4212), this is a reminder and a newer thread to this issue concerning us all !

**Comment by HUMORCE** [comment] 2022-12-29 10:59
Duplicate of #4212

**Closed by HUMORCE** 2022-12-29 10:59 UTC
Labels: enhancement
