### ISSUE TITLE
[Bug] Git doesn't autoupdate properly and can't install older versions

### ISSUE THREAD

**Issue by fv-ian** [ScoopInstaller/Scoop#6162] opened 2024-09-30 17:49 UTC
#### Current Behavior
Unable to install older versions of git

```
❯ scoop install git@2.45.2
WARN  Given version (2.45.2) does not match manifest (2.46.2)
WARN  Attempting to generate manifest for 'git' (2.45.2)
Autoupdating git
Searching hash for PortableGit-2.45.2-32-bit.7z.exe in https://github.com/git-for-windows/git/releases/tag/v$matchTag
The remote server returned an error: (404) Not Found.
URL https://github.com/git-for-windows/git/releases/tag/v$matchTag is not valid
Could not find hash in https://github.com/git-for-windows/git/releases/tag/v$matchTag
Downloading PortableGit-2.45.2-32-bit.7z.exe to compute hashes!
The remote server returned an error: (404) Not Found.
URL https://github.com/git-for-windows/git/releases/download/v$matchTag/PortableGit-2.45.2-32-bit.7z.exe#/dl.7z is not valid
Could not install git@2.45.2
```
#### Expected Behavior
`scoop install git@2.45.2` 

Installs git version 2.45.2

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
```
❯ $($PSVersionTable.PSVersion)

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      5
```

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "shim": "kiennq",
  "last_update": "2024-09-30T10:46:54.2175630-05:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/lukesampson/scoop"
}
```

**Comment by HUMORCE** [comment] 2024-09-30 18:38
Duplicate of #5985

**Closed by HUMORCE** 2024-09-30 18:38 UTC
Labels: bug
