### ISSUE TITLE
[Feature] advice `scoop update *` do not abort when one of the app update fail.

### ISSUE THREAD

**Issue by shishirong** [ScoopInstaller/Scoop#5514] opened 2023-05-23 07:17 UTC
#### Is your feature request related to a problem? Please describe.
as title's describe

#### Describe the solution you'd like
one or little of app fail just let it fail ,do not effect other app update

**Comment by shishirong** [comment] 2023-06-04 15:37
As the same that `scoop reset *`  ,  because all shotcut icon is missing after windows 11 update, I have to use `scoop reset *`  but every reset are abort.

I find the bug issue https://github.com/ScoopInstaller/Scoop/issues/2233 but don't know how to fix it utterly.

**Comment by rashil2000** [comment] 2023-09-05 10:21
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/4135

**Closed by rashil2000** 2023-09-05 10:21 UTC
Labels: enhancement
