### ISSUE TITLE
[Feature] Fallback and try downloading with aria2 disabled when download fails

### ISSUE THREAD

**Issue by redactedscribe** [ScoopInstaller/Scoop#5371] opened 2023-02-02 15:20 UTC
#### Is your feature request related to a problem? Please describe.
Downloading with aria2 enabled (my preferred default) seems to fail more often lately which requires issuing `scoop config aria2-enabled false` before successfully downloading problematic apps. Of course, since using aria2 is my preference, the config option must be set to `true` afterwards.

#### Describe the solution you'd like
If an app download fails with aria2 enabled, automatically retry the same download but with aria2 temporarily disabled. If there are more than one apps to be updated, the next app should first try with aria2, and then fallback to it being temporarily disabled if that download also fails.

Downloads may fail for more reasons than just aria2 being unable to download it, and I'm not sure if Scoop has a way to determine if the fault lies with the resource or aria2's enabled state, but if the resource is at fault, automatically retrying with aria2 disabled would be a quick fail, whereas if the fault lies with aria2 being enabled, it saves time for the user to have to toggle aria2's config pre and post download.

#### Describe alternatives you've considered

I'm not sure what other options there are other than keeping aria2 permanently disabled and accepting slower app update speeds.

Perhaps the higher failure rate that I'm experiencing is to do with using the shim config `kiennq`? I had to set this in the past to overcome an issue with Scoop that I was having but I no longer recall what.

```
aria2-enabled : True
shim          : kiennq
last_update   : 02/02/2023 16:43:50
scoop_repo    : https://github.com/ScoopInstaller/Scoop
scoop_branch  : master
```

**Comment by rashil2000** [comment] 2023-02-02 15:28
Duplicate of #4472.

There's a PR for this too #4292

**Closed by rashil2000** 2023-02-02 15:28 UTC
Labels: enhancement

**Comment by redactedscribe** [comment] 2023-02-02 15:33
It seems my efforts to search GitHub issues relating to aria2 were not successful. Sorry about that.

**Comment by rashil2000** [comment] 2023-02-02 15:36
No worries :)
