### ISSUE TITLE
[Bug] Empty/debug conhost shells created from shims

### ISSUE THREAD

**Issue by brian6932** [ScoopInstaller/Scoop#5505] opened 2023-05-07 23:35 UTC
#### Current Behavior
When shims are opened from explorer/start menu/run, they have to spawn an extra conhost shell, then the program itself as a sub-process.

#### Expected Behavior
This is not ideal, you end up with either an empty shell, or a debug shell, and it looks very ugly for programs like terminal emulators, or browsers. Especially for use cases like wanting to spawn a shell from a path when you're already in explorer, normally you'd just `alt+d`->`program_name`.

#### Possible Solution
Instead there should be some way to contextually start shells. I know there are some Windows API limitations here, but maybe some way toggle `CREATE_NO_WINDOW` as a shim prop, there are prob smarter ways of handling this.

The alternative is to append `$env:PATH` with `env_add_path`, often times this is not ideal, and can lead to path pollution. Another challenge to a solution here would be whether or not it would be possible to launch from some type of symlink-like link to the bin, and having it work as a nested dir, then you could accomplish this effectively without polluting path (I don't believe such a solution is easily possible on Windows, as symlinks and junctions don't behave this way, but maybe there is some type of solution like this).

Before anyone says anything like just `& (scoop which shim | cvpa)`, often times your native shell on Windows will not be pwsh/powershell, so this is simply not feasible.

#### Screenshots
![image](https://user-images.githubusercontent.com/18603393/236707082-a397d987-998f-4082-8a84-1e7591fdbb17.png)
![image](https://user-images.githubusercontent.com/18603393/236707111-12c84155-fff2-47ab-9418-e316d936cbf6.png)
![image](https://user-images.githubusercontent.com/18603393/236708156-5f7f04b7-a2af-430c-9dcc-117e4a98b73f.png)

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.4.0-preview.3

**Comment by rashil2000** [comment] 2023-05-10 17:17
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/1606

**Closed by rashil2000** 2023-05-10 17:17 UTC
Labels: bug

**Comment by brian6932** [comment] 2023-05-10 22:36
That's a bit general, but sure
