### ISSUE TITLE
[Feature] Handle failed updates using `scoop update *` gracefully

### ISSUE THREAD

**Issue by logonoff** [ScoopInstaller/Scoop#5107] opened 2022-08-14 18:05 UTC
#### Is your feature request related to a problem? Please describe.
When `scoop update *` runs and a program fails to update (e.g., `microsoft-jdk` has been broken for the last week), scoop throws an exception and crashes, so all the other programs that are left in queue don't get updated. 

#### Describe the solution you'd like
This suggestion would make it so that `scoop update *` continues to update the rest of the apps despite a failed update. For example, if `microsoft-jdk` fails to update, it would not stop `pwsh` (which is after in the queue) from updating

A drawback could be that this behaviour of stopping the queue is intentional to protect the scoop installation in some way I'm unaware of

#### Describe alternatives you've considered
Rather than making this a default setting, this could be an option in the scoop config.

**Comment by rashil2000** [comment] 2022-08-14 19:01
Tracked here: https://github.com/ScoopInstaller/Scoop/issues/4135

Duplicate of #4135

**Closed by rashil2000** 2022-08-14 19:01 UTC
Labels: enhancement
