### ISSUE TITLE
[Bug] Check config before auto-installing dependencies

### ISSUE THREAD

**Issue by dwettstein** [ScoopInstaller/Scoop#4590] opened 2021-12-21 22:00 UTC
#### Current Behavior
When installing `gcc`, Scoop automatically installs `7zip`, although the config `7ZIPEXTRACT_USE_EXTERNAL` was set to `true`.

#### Expected Behavior
`gcc` installs without installing the `7zip` dependency.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1320

#### Scoop Configuration

```json
{
    "lastupdate":  "2021-12-21T21:47:06.1614275+01:00",
    "SCOOP_BRANCH":  "master",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "MSIEXTRACT_USE_LESSMSI":  true,
    "7ZIPEXTRACT_USE_EXTERNAL":  true
}
```

**Comment by rashil2000** [comment] 2021-12-22 05:52
Duplicate of #3700

**Closed by rashil2000** 2021-12-22 05:52 UTC
Labels: bug

**Comment by dwettstein** [comment] 2021-12-22 19:59
Thanks @rashil2000. I didn't search enough for similar issues. Sorry.
