### ISSUE TITLE
Command to list all bucket's packages

### ISSUE THREAD

**Issue by gavenkoa** [ScoopInstaller/Scoop#4193] opened 2020-12-02 19:08 UTC
I cannot find to list all packages of bucket. 

For example: which java versions are available? To do that I expected to have something like:

    scoop bucket packagesof java

or may be:

    scoop search --bucket java

or even with enhanced search pattern format, like:

    scoop search java/*

**The problem** Today `scoop search java` show nothing interesting (only from buckets `extras` & `main`) because bucket `java` has package names like `adopt12-hotspot` or `zulu15`, nothing that reminds work java literally  ))

**WORKAROUND** Use `scoop search` (without any args). It shows output split by buckets. The list is long, so I recommend to store it to file (`scoop search >list.txt`) or use less (`scoop search | less`).

**Comment by schance995** [comment] 2020-12-10 07:13
Duplicate of #4138
I wrote an alias to do this. It assumes a default install to `~/scoop` and doesn't print app versions.
`scoop alias add allin 'gci "~/scoop/buckets/$($args[0])/bucket" |% { echo "$($_.BaseName)" }' 'List all apps in a bucket'`
For example, `scoop allin main` prints all apps in main.

**Comment by gavenkoa** [comment] 2020-12-10 10:33
There is slowdown if I try to filter `scoop list` as it loads all bucket definition (and might trigger updates on all buckets)...

`'gci "~/scoop/buckets/$($args[0])/bucket" |% { echo "$($_.BaseName)" }'` is cool but I'd like to see it built-in `scoop bucket allin $pkg` because `~/scoop/buckets/$($args[0])/bucket` is internals that might change one day...

Is it realistically to contribute to the project?

I see `scoop bucket allin` / `scoop bucket packagesof` or may be `scoop bucket dump $bucket` as an interface to the feature. If it is OK I could try to implement.

**Comment by rashil2000** [comment] 2022-01-13 06:15
Tracked in #4138

**Closed by rashil2000** 2022-01-13 06:15 UTC

**Comment by bledari** [comment] 2022-03-23 15:15
This is not the same as https://github.com/ScoopInstaller/Scoop/issues/4138. You should reopen this I guess

**Comment by gavenkoa** [comment] 2022-03-28 18:47
> What's the use case?

It is common for package manager to have search built-in:

```
apt-cache search node
dnf search node
```

and the search is performed using package **metadata** (not only by *name* but also by *description*):

> dnf [options] search [--all] <keywords>...
>    Search package metadata for keywords. Keywords are matched as case-insensitive substrings, globbing is supported. By default lists packages that match all requested keys (AND operation). Keys are searched in package **names** and **summaries**. 

> apt-cache search is a very rudimentary tool, basically implementing grep on package's **descriptions**.

There is high probability I find packages related to Node  or Java through **description**, not only name.

**Comment by rashil2000** [comment] 2022-03-28 19:28
https://github.com/ScoopInstaller/Scoop/issues/4412
