### ISSUE TITLE
[Feature] Is it a good idea to configure scoop so that one bucket can be prior to another one?

### ISSUE THREAD

**Issue by NamelessUzer** [ScoopInstaller/Scoop#5139] opened 2022-09-06 16:01 UTC
#### Is your feature request related to a problem? Please describe.

Always I add not only the bucket "main", "extras", but also some other buckets, such as "apps". The bucket "apps" has the same software as the bucket "extras". When I install software, sometimes, scoop install them from the bucket "apps". then the bucket "extras" update the software I installed from the bucket "apps". But I cannot update this software as it's installed via the bucket "apps". If I install software via the bucket "extras", then I cannot get updates from the bucket "apps".

#### Describe the solution you'd like

Is it a good idea to configure scoop so that one bucket can be prior to another one? For example, I prefer the bucket "extras", I am willing to config scoop to install software from the bucket "extras" first, then the bucket "apps", then some other buckets.

#### Describe alternatives you've considered

Give users an option that always keeps updating to the latest version, no matter which bucket it comes from.

**Comment by rashil2000** [comment] 2022-09-06 16:04
Duplicate of #5131

**Closed by rashil2000** 2022-09-06 16:04 UTC
Labels: enhancement

**Comment by NamelessUzer** [comment] 2022-09-06 16:19
Sorry.
