### ISSUE TITLE
Improve Search Performance

### ISSUE THREAD

**Issue by JustinGrote** [ScoopInstaller/Scoop#4239] opened 2021-01-21 21:44 UTC
https://github.com/shilangyu/scoop-search has changed my experience with scoop, the slow search has always been one of my pain points as a user.

I'd be willing to PR improvement to the search engine to incorporate the lessons learnd here if there is interest.

**Comment by Bios-Marcel** [comment] 2021-08-03 10:40
I've made a pull request with a simple improvement. There' still room for more improvement, but this already cuts the search by 60-70 percent, which is good enough for me :D

**Comment by Bios-Marcel** [comment] 2021-08-03 10:50
It appears that the problem is that we parse the whole json. Maybe we can try to switch this to an approach where we only parse until we find the `bin` section?

**Comment by rashil2000** [comment] 2022-01-14 18:08
> I'd be willing to PR improvement to the search engine to incorporate the lessons learnd here if there is interest.

Yes! Please make a PR when you can.

**Comment by bartvanandel** [comment] 2022-03-16 11:35
I was annoyed by this myself, so I've just put some effort in writing a fix for this. Will publish a PR soon.

**Comment by cigh033** [comment] 2023-06-27 13:14
I managed to reduce search time by almost 99%
Because I wanted to keep the core search intact (and I don't understand a bit what is going on under the hood), I built myself an additional command, that builds a cache file containing binaries, names and descriptions of all apps in all local buckets, and added a parameter to scoop search (--offline) that just searches this index file.

```console
╭─sb@tealc ~
╰─$ time scoop search lazygit
Results from local buckets...

Name    Version Source Binaries
----    ------- ------ --------
lazygit 0.38.2  extras
00:00:18.2134557

╭─sb@tealc ~
╰─$ time scoop search lazygit --offline
Results from cached list...

Name    Version Source Binaries
----    ------- ------ --------
lazygit 0.38.2  extras lazygit.exe
00:00:00.1915792
```
For my use case this really is enough. I do not know if this is a valid approach for any of you, i just wanted to share the idea.

Cheers

**Comment by Bios-Marcel** [comment] 2023-06-28 08:53
Awesome idea @cigh033 

Sounds like something worth adding, but not invoke by default.

**Comment by Yakiyo** [comment] 2023-08-31 14:45
@cigh033 generating a cache file would indeed make subsequent searches faster, but the initial invokation would need the same, if not more amount of time as the original search command right? and wouldn't the cache file need to be updated after certain intervals too?

**Comment by rashil2000** [comment] 2023-09-10 18:46
> I narrowed down the regression in search times to the cmdlet `manifest_path` in `manifest.ps1`. With the current version
> 
> ```
> function manifest_path($app, $bucket) {
>     (Get-ChildItem (Find-BucketDirectory $bucket) -Filter "$(sanitary_path $app).json" -Recurse).FullName
> }
> ```
> 
> I get the 20 second search times but with the previous
> 
> ```
> function manifest_path($app, $bucket) {
>     fullpath "$(Find-BucketDirectory $bucket)\$(sanitary_path $app).json"
> }
> ```
> 
> It goes down to 8 seconds.
> 
> It seems like the new version is searching for a file in all subdirectories. Is this really necessary? Don't all manifests have to be always located in `bucket/`?
> 

_Originally posted by @mathijshenquet in https://github.com/ScoopInstaller/Scoop/issues/5615#issuecomment-1694653931_

> Don't all manifests have to be always located in `bucket/`?

Historically, manifests were also present in the root directory. However most buckets now follow the convention of having a `bucket/` subdirectory, in order to keep the repo cleaner.

**Comment by xialvjun** [comment] 2023-10-19 08:23
Just an advice: maybe we can use sqlite or moreover we can use a git like sql databse like https://github.com/dolthub/dolt

**Closed** 2024-04-18 16:08 UTC
