### ISSUE TITLE
ffmpeg install error with 404 non-existent url

### ISSUE THREAD

**Issue by WMCB-Tech** [ScoopInstaller/Scoop#4589] opened 2021-12-21 07:32 UTC
scoop returns 404 error when installing ffmpeg (`scoop install ffmpeg`)
```
WARN  Purging previous failed installation of ffmpeg.
Uninstalling 'ffmpeg' ().
'ffmpeg' was uninstalled.
Installing 'ffmpeg' (4.4.1-2) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-12-07-12-23/ffmpeg-n4.4.1-2-gcc33e73618-win64-gpl-4.4.zip is not valid
```
saw similar issue to #4419 
and perhaps alternate download sources could be used instead of autobuilds one which it deletes releases later

**Comment by rashil2000** [comment] 2021-12-21 07:34
Duplicate of https://github.com/ScoopInstaller/Main/issues/3113

**Closed by rashil2000** 2021-12-21 07:34 UTC
Labels: bug
