### ISSUE TITLE
Checkver before install

### ISSUE THREAD

**Issue by flt6** [ScoopInstaller/Scoop#5749] opened 2023-12-03 05:33 UTC
#### Is your feature request related to a problem? Please describe.

Some package download URL is outdated, so Scoop cannot install it.

#### Describe the solution you'd like

Most of them can be fix simply use `checkver` and URL of `autoupdate` instead of the default download URL, user and developer can specific whether use `autoupdate` or not. Developer can confirm if their bucket URL can be refresh this way.

**Comment by HUMORCE** [comment] 2023-12-27 22:55
In most cases of **cannot install**, it caused by wrong url, not url outdated.

Apps released as semver or fixed url will essentially not facing the issue.

- For semver: May have been installed a older version of app, because apps released as semver will essentially not remove recent verions soon.
- For fixed url: May have been installed an latest version of the app, but the manifest version still shows up as an older version.
- Others: If one of checkver/autoupdate does not work, then check it locally again will not help the users get a correct(new) download url, because autoupdate only updates captured/defined variables not full url.
- If you know that a new version of the app has been released, and both checkver/autoupdate are available, but the excavator(gh action for bucket) has not updated it yet.
  - Waiting for update
  - Update the manifest locally and install/update the app, then restore the bucket repo(for preventing conflicts

**Comment by goyalyashpal** [comment] 2024-04-12 14:26
can this be closed?

**Closed** 2024-04-12 15:50 UTC
Labels: enhancement
