### ISSUE TITLE
[Bug] gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by knightknight** [ScoopInstaller/Scoop#6174] opened 2024-10-07 09:36 UTC
#### Current Behavior
```bash
scoop update *
```

#### Expected Behavior
Updater autodetects and runs.

#### Additional context/output

```bash
gimp: 2.10.38 -> 2.10.38-1

Updating 'gimp' (2.10.38 -> 2.10.38-1)
Downloading new version
Loading gimp-2.10.38-setup-1.exe from cache
Checking hash of gimp-2.10.38-setup-1.exe ... ok.
Uninstalling 'gimp' (2.10.38)
Installing 'gimp' (2.10.38-1) [64bit] from 'extras' bucket
Loading gimp-2.10.38-setup-1.exe from cache
Extracting gimp-2.10.38-setup-1.exe ... ERROR Exit code was 1!
```

```bash
# ~\scoop\apps\gimp\2.10.38-1\innounp.log

Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.4.5

#### Scoop Configuration
```json
{
  "aria2-enabled": false,
  "last_update": "2024-10-07T10:18:57.5598641+01:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/lukesampson/scoop"
}
```

**Comment by HUMORCE** [comment] 2024-10-11 07:17
Duplicate of #6169

**Closed by HUMORCE** 2024-10-11 07:17 UTC
Labels: bug
