### ISSUE TITLE
[Bug] Error when there are no matches found.

### ISSUE THREAD

**Issue by Absolves** [ScoopInstaller/Scoop#4588] opened 2021-12-17 17:26 UTC
#### Current Behavior

Search for software that is not in the buckets
#### Expected Behavior

Reply "No matches found."
#### Additional context/output

Error message appears：

invoke-webrequest : {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/git#get-a-tree"}
At C:\Users\WDAGUtilityAccount\scoop\apps\scoop\current\libexec\scoop-search.ps1:52 char:15
+     $result = invoke-webrequest $url -UseBasicParsing | Select-Object ...
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
No matches found.

(Besides: I get the same result on the virtual machine and the host.)

### System details

**Windows version:** [e.g. 7, 8, 10]
Windows 11
**OS architecture:** [e.g. 32bit, 64bit]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
Major  Minor  Build  Revision
5      1      22000  282
**Additional software:** [(optional) e.g. ConEmu, Git]
Git
#### Scoop Configuration

```json
//# Your configuration here
{
    "lastupdate":  "2021-12-18T01:13:50.7384580+08:00"
}
```

**Comment by HUMORCE** [comment] 2021-12-17 18:30
```
> scoop search jklajskljkljkl
No matches found.
```

cannot reproduce.

**Comment by Absolves** [comment] 2021-12-17 19:49
> ```
> > scoop search jklajskljkljkl
> No matches found.
> ```
> 
> cannot reproduce.

I reinstalled scoop in Windows sandbox, but it did report an error. I then tested it again on my other windows 10 computer and the same error appeared. I am not sure if this is a personal problem in my installation. I typed the following commands in order.
'''
Set-ExecutionPolicy RemoteSigned -scope CurrentUser
iwr -useb get.scoop.sh | iex
'''
Exactly as the official one. But it comes up with the error.
'''
PS C:\Users\WDAGUtilityAccount> scoop search jklajskljkljkl
invoke-webrequest : {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/git#get-a-tree"}
At C:\Users\WDAGUtilityAccount\scoop\apps\scoop\current\libexec\scoop-search.ps1:52 char:15
+ $result = invoke-webrequest $url -UseBasicParsing | Select-Object ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
No matches found.
InvokeWebRequestCommand No matches found. 
'''
If possible, you can try to install scoop in Windows sandbox to test it. I'm sorry I don't know much about powershell, so I can't provide more information. If there is anything you need, please feel free to contact me.

**Comment by ilkka** [comment] 2021-12-17 20:16
Win11 here, scoop just started doing this for me too today, probably after my near-daily `scoop update *` ritual

**Comment by ilkka** [comment] 2021-12-17 20:18
Walp, feel a bit stupid now, but apparently another `scoop update` just fixed this problem for me.

**Comment by rashil2000** [comment] 2021-12-18 03:20
Duplicate of #4574

**Closed by rashil2000** 2021-12-18 03:20 UTC
Labels: bug
