### ISSUE TITLE
[Bug] In PowerShell, if `git` is an alias several operations break

### ISSUE THREAD

**Issue by giggio** [ScoopInstaller/Scoop#5932] opened 2024-04-30 21:47 UTC
#### Current Behavior
If you have `git` set to an alias scoop fails in some operations. I noticed so far: update and export.

#### Expected Behavior
These operations work.

#### Additional context/output

To reproduce:

Install hub: https://hub.github.com/

```powershell
Set-Alias git hub
```

Try to run scoop export:

```powershell
scoop export --config
# InvalidOperation: C:\Users\user\scoop\apps\scoop\current\lib\core.ps1:273
# Line |
#  273 |          return & $git @ArgumentList
#     |                   ~~~~
#     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
```

Or update:

```powershell
scoop update
# Scoop uses Git to update itself. Run 'scoop install git' and try again. 
```

#### Possible Solution
Temporary workaround: remove the alias:

```powershell
Remove-Alias git
```

### System details

**Windows version:** `11 (Microsoft Windows [Version 10.0.22631.3527])`

**OS architecture:** 64bit

**PowerShell version:** `7.4.2` (Also fails in Windows PowerShell)

**Additional software:** N/A

#### Scoop Configuration

```json
{
  "last_update": "2024-04-30T18:18:37.3207233-03:00",
  "scoop_repo": "https://github.com/lukesampson/scoop",
  "scoop_branch": "master"
}
```

**Comment by HUMORCE** [comment] 2024-05-11 11:22
Duplicate of #5196

**Closed by HUMORCE** 2024-05-11 11:22 UTC
Labels: bug
