### ISSUE TITLE
[Feature request] Multiple installation locations.

### ISSUE THREAD

**Issue by marknefedov** [ScoopInstaller/Scoop#5608] opened 2023-08-11 19:17 UTC
#### Is your feature request related to a problem? Please describe.
Currently, Scoop installs applications in the user's home directory under `$HOME/scoop`. However, users may want to install applications in different locations for various reasons, such as:

- Installing on different disks to manage storage space
- Separating development SDKs and tools from regular programs
- Installing applications on a Windows development drive

I want to install SDKs and dev caches to new [Windows Dev drive](https://learn.microsoft.com/en-us/windows/dev-drive/), but do not want to pollute it with other software.

#### Describe the solution you'd like
Add support for multiple install locations in Scoop, allowing users to install applications and tools in different directories based on their preferences and use cases.

#### Proposed Solution
Extend Scoop's functionality to support multiple install locations by allowing users to specify custom installation paths during the installation process. This can be achieved by adding a new command-line option, such as `--install-path`, which accepts a custom directory path as its argument.

For example:

```
scoop install --install-path "D:\Development\Tools" git
```
This command would install the `git` application in the specified directory, `D:\Development\Tools`.
`D:\Development\Tools` content will mirror current installation directory structure with `apps`, and `persist` sub-directories. (It would probably be better to call such folders installation libraries)

**Comment by rashil2000** [comment] 2023-10-02 09:20
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/3559

**Closed by rashil2000** 2023-10-02 09:20 UTC
Labels: enhancement

**Comment by geekalert** [comment] 2023-12-18 19:40
@rashil2000 Please reenable this feature request. @marknefedov created this feature request as a result of that conversation, so close it seems unhelpful. This is still avery requested f3eature. In fact, I came to chime in about it, only to find it closed. Was it ever implemented?

**Comment by rashil2000** [comment] 2024-01-05 18:28
No, this wasn't implemented. 

The end goal of this issue and #3559 is the same - hence I closed this. I'd like to keep discussion pertaining to a particular problem in the same place.
