### ISSUE TITLE
Support shims to both console and GUI apps

### ISSUE THREAD

**Issue by prasannavl** [ScoopInstaller/Scoop#1606] opened 2017-07-18 09:15 UTC
When using any tools, like `sysinternals` for example, an empty command window (the shim) is open, and has to be manually closed. 

The ideal way would be that the shim itself be a "win32" app. Currently all shims are console programs. i.e, not linked as "win32" apps for gui mode.

EDIT:
Suggestion, allow for properties in the manifest to configure which binaries are gui shims, and which should be commandline shims, and use shims accordingly.

**Comment by SimplyKnownAsG** [comment] 2018-03-01 18:24
would it be possible to add a flag in the json (then in the .shim) indicating that shim.exe should not wait indefinitely? Something like

```C#
bool fork = bool.Parse(Get("fork", config) ?? "false");
if(fork) {
    return 0;
}
else {
    WaitForSingleObject(pi.hProcess, INFINITE);

    uint exit_code = 0;
    GetExitCodeProcess(pi.hProcess, out exit_code);

    // Close process and thread handles.
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);

    return (int)exit_code;
}
```

I'm not sure how one might specify this in the `app.json`, and currently it looks like `function shim` within `core.ps1` would need to accept another argument. It might make sense (for future concerns) to allow `$arg` to be a dict of key/vals that can be dumped to the `.shim` file for loading. Not to get ahead of this current problem.

**Comment by SimplyKnownAsG** [comment] 2018-03-13 23:38
@r15ch13 is there a way you think this should be accomplished? i'd be happy to close #2006 if there were another way around it. I suppose we could also change GUIs to just add the path rather than creating a shim. is there a preference of adding to path vs creating a shim?

**Comment by Congee** [comment] 2018-05-25 15:23
A symbolic link would suffice. BTW, why do we need a `shim.exe`?

**Comment by rasa** [comment] 2018-05-25 16:18
A symbolic link doesn't work, as the exe that is the symlink's target cannot find its related .dlls, as the "exe's directory" is the directory the shim is in, not where the target lives.

**Comment by SimplyKnownAsG** [comment] 2018-05-25 17:03
Windows isn't very friendly about symbolic links, but hard links are more accessible for those who do not have admin rights. However, I think that @rasa is correct about `.dll`s.

@Congee, I'm not sure I understand the question:
> why do we need a `shim.exe`?

I think the intent of `scoop/shims/*.exe` is used to help prevent pollution of the `PATH`. `shim.exe` is a fancy/funky symlink

**Comment by fritzmg** [comment] 2018-11-22 16:21
> > why do we need a `shim.exe`?
> 
> I think the intent of `scoop/shims/*.exe` is used to help prevent pollution of the `PATH`. `shim.exe` is a fancy/funky symlink

Additionally, if you create file assocations or any other reference for an application that is installed via scoop, they would not work anymore if the application gets updated (since the folder name would change).

Btw. it appears that icons from the "shim"ed (?) executable also do not work: https://stackoverflow.com/questions/53430845/scoop-installed-git-bash-open-git-bash-here-context-menu

**Comment by r15ch13** [comment] 2018-11-22 18:00
@fritzmg the actual [`shim.exe`](https://github.com/lukesampson/scoop/tree/master/supporting/shimexe) doesn't have an icon, so it can't be displayed.
In this case, it's recommended to use the `current` version path. (e.g. `~\scoop\apps\git\current\git-bash.exe`)

**Comment by fritzmg** [comment] 2018-11-23 08:52
Ah yes, thank you, just noticed your answer on stackoverflow too :)

**Comment by excitoon** [comment] 2018-12-20 12:19
> 
> 
> would it be possible to add a flag in the json (then in the .shim) indicating that shim.exe should not wait indefinitely? Something like
> 
> ```cs
> bool fork = bool.Parse(Get("fork", config) ?? "false");
> if(fork) {
>     return 0;
> }
> else {
>     WaitForSingleObject(pi.hProcess, INFINITE);
> 
>     uint exit_code = 0;
>     GetExitCodeProcess(pi.hProcess, out exit_code);
> 
>     // Close process and thread handles.
>     CloseHandle(pi.hProcess);
>     CloseHandle(pi.hThread);
> 
>     return (int)exit_code;
> }
> ```
> 
> I'm not sure how one might specify this in the `app.json`, and currently it looks like `function shim` within `core.ps1` would need to accept another argument. It might make sense (for future concerns) to allow `$arg` to be a dict of key/vals that can be dumped to the `.shim` file for loading. Not to get ahead of this current problem.

Totally agree.

**Comment by r15ch13** [comment] 2018-12-20 17:48
@excitoon how would this console/GUI check look like? Is that possible?

**Comment by excitoon** [comment] 2018-12-20 20:37
I just made a PR for that.

**Comment by excitoon** [comment] 2018-12-24 09:33
As for second part, icon for shim, there are two ways doing it:
1) make shell handler which would set proper icon for a file (quite system-intrusive);
2) simply copy icon from executable into shim (PE format is well described and static).

**Comment by fcying** [comment] 2019-02-04 05:34
Can it add a parameter? ex `scoop install aaa --gui`, then it create shims as a gui app.

**Comment by yelkarama** [comment] 2019-04-06 19:10
Hi 
Chocolatey is also using the same shim technique to (I believe) avoid polluting the path and it doesn't have this issue. 
Here is their github repo:
[https://github.com/chocolatey/shimgen](https://github.com/chocolatey/shimgen)

**Comment by h404bi** [comment] 2019-04-26 10:00
@yelkarama shimgen of chocolatey is a **closed source proprietary software**, though they say it's an open source feature in [their docs title](https://chocolatey.org/docs/features-shim#shimming---automatically-add-executables-to-path-free-open-source), kinda funny.

You know that Scoop is a person project of luke, while Chocolatey is a commercial software, though it has community version. The distribution or use of shimgen outside of Chocolatey without permission is prohibited. The shimming system is a critical piece of Scoop/Chocolatey, obviously. Scoop community developers will always be interested in improve the project, but as you know it's still a commnity maintained project, thus it can take more time. :)

**Comment by excitoon** [comment] 2019-04-26 10:24
@yelkarama Your link you posted is only a readme and issue list.

**Comment by niheaven** [comment] 2019-04-26 13:07
> I want to use shimgen outside of Chocolatey.
> 
> If your project is FOSS, please contact us for a grant of a free license to do so. > If your project is commercial, please contact Chocolatey Software for a quote.

shimgen is closed source proprietary software, while generated shim is under MS-RSL...

**Comment by rasa** [comment] 2020-12-23 15:21
This issue should be fixed in #3998, which was merged into master. To use, type:
```
scoop config shim kiennq
scoop reset *
```
or
```
scoop config shim 71
scoop reset *
```
Eventually, one of those shims (probably kiennq) we be made the default. 

If this issue is still a problem after trying both solutions above, please reopen this issue. Thanks!

**Comment by hinogi** [comment] 2021-04-02 18:52
I guess this still is an issue

**Comment by street-grease-coder** [comment] 2021-07-14 12:50
seems to be still an 'issue' as of July, e.g., with notepad++ when using win+r ('run')

> I guess this still is an issue
> for example if you install and run https://wezfurlong.org/wezterm/install/windows.html

**Comment by syncrodazt** [comment] 2021-08-04 00:12
Why do I get this error when running both of these commands?

> ```
> scoop config shim kiennq
> scoop reset *
> ```

> ```
> scoop config shim 71
> scoop reset *
> ```

![image](https://user-images.githubusercontent.com/9114084/128101457-f291d9a3-5f2e-45ee-8b43-857b205f6b0c.png)

**Comment by Yazir** [comment] 2021-08-04 21:58
@syncrodazt try doing
`scoop update -f 7zip`

And speaking of the feature itself. I very much like it. I am a new scoop user and it bothered me when i went windows key -> type 'git bash' -> have cmd and git bash open up.

It's been like this with most apps ran through windows quick access. With the shim config it's solid now.

**Comment by FelixZhang** [comment] 2022-06-20 03:27
I'm seeing this issue again since a recent update on sumatrapdf

**Comment by sinni800** [comment] 2022-06-20 04:53
Multiple of the apps I have installed still show the blank cmd windows when I run the shim executables. Ones that are console anyway will use that console window, but ones that are GUI, this console window does nothing, and closing it closes the app.

Notably, git-gui and Blender (I think Blender runs DeallocConsole though to get rid of it, because opening a console first is Blender's default behaviour) work fine, while some examples like notepad2 do not. Also, the ones that create entries in the start menu through the "scoop apps" folder are also fine, but those don't use the shim exeuctable anyway. Those GUI apps that don't make such an entry, those will be the ones directly found by the executable in start menu search and those still suffer for me.

**Comment by rashil2000** [comment] 2022-06-20 08:09
Which shim executable are you using? Can you run this and try again?

```
scoop config shim kiennq 
scoop update
scoop reset *
```

**Comment by rashil2000** [comment] 2022-06-20 13:03
Ah okay I think I understand the issue now. The shim executable is a console program, so it will always open a console regardless of whether the target executable is a console program or a GUI program. Note that this is a peculiarity of Windows itself, all programs need to declare what subsystem they belong to (either CONSOLE or WINDOWS) before compilation and there's no way to work around this.

Programs which have a GUI should create shortcuts for themselves in the manifest. Using the shim for them is not recommended, the shim is only supposed to be used from the shell/terminal.

**Comment by sinni800** [comment] 2022-06-20 14:47
Well, there are solutions I can personally think of.

I know for console apps you can't just not wait for execution to end (or else the console will dealloc), and for it to stay in the same console session, you have to execute the app in your own console session... I get that this is why scoop does it this way. 

I can see a few solutions to this. 

First, actually read the PE info of the executable and ShellExecuteEx it if it's a gui app (then don't wait and the shim will pop up a console but at least disappear). 

Other solutions I havd would need the manifest to include information about the nature of the app though...

Here, I can see generating different shims whether or not the app is a gui app - something like Blender would say it's a console app (because it does always start up with a console first), for example. A gui shim is a gui executable, while a console shim is as now. Make the default console and you only have to update the gui apps (least destructive way).

Second, use the ".shim" file to determine this state, then the shim, when reading that, decides to DeallocConsole at runtime or, here, again, ShellExecuteEx the executable instead. 

Since we're on Windows, unlike on Linux, the parent process can die without taking its children with it.

**Comment by rashil2000** [comment] 2022-06-20 19:26
I mean I understand there are workarounds for it (which will require a lot of hard work and special casing, for e.g. not all target executables are .exe files etc.), but I still don't understand the point of this effort. GUI apps have shortcuts already (which directly target the app executable), why would you want to launch them using a shim, and that too directly from Start Menu (where the said shortcuts exist)? Shims are a CLI tool by definition: they should be used only from the CLI.

**Comment by sinni800** [comment] 2022-06-20 20:04
Well, the use case is that some (gui) applications are very good to run from a console or the "RUN" field, like notepad++ or notepad2. The console blocking on that is actually kind of annoying here. 

Of course, assigning the filetype to that app also works, but you can only have one app assigned to a file type. 

I get some apps actually use bat/cmd and not exe. In that case, the special case is just this: If exe, do PE introspection, if not, do nothing at all and behave like before. 

As for the analysis though, I have done some Google-Fu, and there is a class for PE Headers in... dotnet v6. Since scoop needs to run on the basic windows included Powershell, that's out. There is a c# library that should fit in the requires versions, but yeah, it's a lot more work than I thought to do the analysis here. https://github.com/secana/PeNet 

With the dotnet v6 class it would be a handful of lines to find the subsystem type in the PE header.

**Comment by rashil2000** [comment] 2022-06-20 20:09
BTW the current shim does not use C# at all, it's written in C++: https://github.com/kiennq/scoop-better-shimexe

**Comment by sinni800** [comment] 2022-06-20 23:04
I meant do the check in powershell code, to scope it to scoop itself

**Comment by r15ch13** [comment] 2022-06-21 20:00
Getting the subsystem from the PE header shouldn't be that difficult.
https://www.fuzzysecurity.com/tutorials/20.html
Just the header size and some offsets.

**Comment by gerardog** [comment] 2022-06-23 23:57
My two cents:
Shims are a correct approach to add to the path both CLI and GUI apps. Think of `notepad++ file.txt`, it should open a GUI app and free the console right away. Shortcuts won't pass thru the arguments, Symlinks generate loading problems on many apps.

But, a CLI Shim should be generated for CLI apps, and a GUI shim for GUI apps. The shim source code itself would be the same, but the subsytem must change to generate a GUI or CLI app. Maybe (pure especulation! sorry if Im wrong) the same compiled shim can be fixed: the subsystem can be changed with an hex editor, just flipping the PE bit.

I believe this PR was in that direction: #2921

Alternatively, the shim itself can check if the target app is GUI or CLI, and return immediately for GUI apps. The sideeffect is that if you, for example, type Win+R and run an scoop installed GUI app, a console window will open and close immediately.

**Comment by gerardog** [comment] 2022-06-24 00:28
Kiennq shim has code to handle this gracefully since it was implemented: see [shim.cpp#L217](https://github.com/kiennq/scoop-better-shimexe/blob/v3.0/shim.cpp#L217). Not sure why is it failing.

**Comment by sinni800** [comment] 2022-06-24 03:40
Yeah the hiword of SHGFI_EXETYPE in ShGetFileInfoW should be 0 for console apps (whether they're MZ or PE) and the windows version (so different than 0) for a "Windows Application", I think that implies a gui app?

I do wonder what's going wrong with it then. On a quick Google Ive seen reports of people saying that this winapi function sometimes locks for them on Windows 10, if it does that, that would explain why it gets stuck. Though that's an absolute shot in the dark at this moment.

But also, I very faintly remember that FreeConsole can fail silently. Do the in, out and err streams maybe have to be closed first? Those are pre-attached on startup since it's a console app after all. That is, fclose on all three. 

Im not very experienced with c/c++ to be honest, but we either have to carry this issue over to the shim (because the FreeConsole doesnt seem to be doing what it should do) or touch on different solutions (generating different shims, maybe only with the subsystem adjusted). The most beautiful goal would be not having a window pop up at all. But they should definitely not stay for gui apps. 

Maybe generating a different shim whether it's a gui or cui app would be the better overall solution.

**Comment by rashil2000** [comment] 2022-06-24 06:14
> Kiennq shim has code to handle this gracefully since it was implemented: see [shim.cpp#L217](https://github.com/kiennq/scoop-better-shimexe/blob/v3.0/shim.cpp#L217). Not sure why is it failing.

@kiennq would you happen to have idea why this isn't working?

**Comment by sinni800** [comment] 2022-06-24 11:34
So I just checked on my other computer and can confirm the issue there too. So I think this is not just me

**Comment by pfmoore** [comment] 2022-06-24 11:34
@rashil2000 the problem is that the `path` argument is quoted, so `SHGetFileInfoW` returns "The filename, directory name, or volume label syntax is incorrect". There's no error handling on the `SHGetFileInfoW` call, so this problem is not reported, but the return value of 0 is treated as the executable type (which then translates to "not a Windows executable"...

Fixing this isn't too hard if you don't mind allocating a new string. Something like this seems to work (but I'm *not* a C++ expert, so ideally someone else can make this cleaner):

```C++
    auto newpath = path;
    if (path && path->length() >= 2 && path->front() == L'"' && path->back() == L'"') {
        newpath = path->substr(1, path->length() - 2);
    }
```

**Comment by pfmoore** [comment] 2022-06-24 14:38
One thought - I've no idea if a quoted `path` could have escaped quotes inside - something like `"C:\Some\Path \"with quotes\"\etc"`. If so, simply stripping the outer quotes might not be enough. The documentation for `CreateProcess` isn't at all clear how to quote paths which contain both spaces and double quote characters, and honestly it's probably a pretty rare case. But it might at least be worth checking for it and giving a friendly message if it comes up.

**Comment by sinni800** [comment] 2022-06-24 14:48
Well, Windows doesnt allow quotes in file and folder names, so I think this should be a non issue. Also, even if the file system actually allows it, if someone has actual quote signs in their directory paths... that's kind of horrifying.

**Comment by pfmoore** [comment] 2022-06-24 14:52
> Well, Windows doesnt allow quotes in file and folder names

Oh, cool. I'd forgotten that. So this is a non-issue, good. Using `PathUnquoteSpacesW` sounds like a much more robust approach, though.

**Comment by pfmoore** [comment] 2022-06-24 15:50
https://github.com/kiennq/scoop-better-shimexe/pull/6

**Comment by rasa** [comment] 2022-06-24 19:54
Should we have a separate GUI shim, where the exe of the shim itself says it's a GUI app? 

Or is kiennq's [GUI sensing logic](https://github.com/kiennq/scoop-better-shimexe/blob/75edd096dfd30dd0088ec72c783f921a038b0cb5/shim.cpp#L219) enough?

**Comment by pfmoore** [comment] 2022-06-24 21:31
A separate shim would avoid flashing a console when double clicked. But personally, I don't care much about that use case, and we'd need extra code to decide which shim to use (how easy is it to determine if the target is a GUI or console executable from Powershell?)

I'm happy not to bother, but others may disagree - I'm new here, after all 🙂

**Comment by sinni800** [comment] 2022-06-24 21:31
Well, the ideal would be to have a separate gui shim that doesnt open a console window at all. To be honest, I would vote for that alternative

**Comment by pfmoore** [comment] 2022-06-24 22:32
Yes, I thought of that, but I wasn't willing to try to work out how to detect a file's subsystem in Powershell, and modify the shim installation code, as well as working out how to build and ship two shims. I was happy enough to be able to identify and fix the bug in the existing approach.

I'm more than happy if someone else wants to tackle the idea of having two shims, though.

**Comment by rasa** [comment] 2022-06-25 14:02
> A separate shim would avoid flashing a console when double clicked. 

@cqjjjzr in https://github.com/kiennq/scoop-better-shimexe/pull/3#issue-1185754616 says "a blank console window ... may be suppressed via CREATE_NO_WINDOW creation flag, but I don't know if it would break other things.."

**Comment by pfmoore** [comment] 2022-06-25 14:21
Nope, the console window is created as a result of double clicking on the *shim* (which is a console app). The shim can close the console window via `FreeConsole` (which it does) but it can't prevent the OS opening that console window, at least briefly, without being a GUI app (which wouldn't work as a shim for a console app, which is the normal case).

**Comment by excitoon** [comment] 2022-06-25 15:33
What's problem, didn't I already fix that?

**Comment by excitoon** [comment] 2022-06-25 15:37
Ah, I see, @rasa waited 2 years before closing my PR and telling that is not needed anymore.

**Comment by excitoon** [comment] 2022-06-25 15:37
Then what is the problem?

**Comment by kltk** [comment] 2022-06-27 04:13
> Nope, the console window is created as a result of double clicking on the _shim_ (which is a console app). The shim can close the console window via `FreeConsole` (which it does) but it can't prevent the OS opening that console window, at least briefly, without being a GUI app (which wouldn't work as a shim for a console app, which is the normal case).

Are there any problems with GUI applications?

---

maybe refer to [nirsoft advancerun](nirsoft.net/utils/advanced_run.html)

**Comment by rasa** [comment] 2022-06-27 06:28
I reopened https://github.com/ScoopInstaller/Scoop/pull/2921 as it creates separate shims for both cli and gui, as @excitoon [says](https://github.com/ScoopInstaller/Scoop/pull/2921#issuecomment-1166312058) a single shim can't "automatically determine [the] application subsystem."

**Comment by rashil2000** [comment] 2022-06-27 09:59
kiennq's repo is the correct place for the PR. It seems they might be a little busy, and we don't have permissions on that repo.

**Comment by gerardog** [comment] 2022-06-27 23:45
It may be a good time to clean the shim duplicates. AFAIK there are 3 different Shims source codes around:

*1. https://github.com/ScoopInstaller/Shim
*2. https://github.com/ScoopInstaller/Scoop/tree/master/supporting/shimexe
*3. https://github.com/kiennq/scoop-better-shimexe

Additionally: kiennq's build output is uploaded to: 

 *4. https://github.com/ScoopInstaller/Scoop/tree/master/supporting/shims/kiennq

This creates some confusion... for example in @excitoon PR #2921: while adds proper GUI/CLI shim deployment, it also changes the build of the outdated shim *2 (*4 was already being used).

It may be a good time for Scoop to own it's Shim. I suggest ScoopInstaller/Shim be reseted to pfmoore/scoop-better-shimexe.

Please note that the build process must be fixed to generate both GUI/CLI outputs.

**Comment by gerardog** [comment] 2022-06-27 23:56
I just remembered my old PR, which goes in that direction: ScoopInstaller/Shim#3 😊

**Comment by couleurm** [comment] 2022-06-28 12:21
Hey, wouldn't it be a good idea to make the decision in the `foo.shim` ?

```
path = "Scoop\apps\foo\current"
args = "bar"
type = gui
```

Users would be able to easily switch instead of making different type of hard-coded binaries

(not assuming I have any technical knowledge regarding if it needs to know if it's gonna have a window right away or can read the .shim before making a decision)

**Comment by SpacewaIker** [comment] 2024-01-15 23:08
@spider2048 your changes in #5559 and #5684 don't seem to work on my computer. I switched to the develop branch and tested with both neovide and nvim-qt, both stay attached to the terminal. (I do get the message that a GUI application was detected when installing)

**Comment by spider2048** [comment] 2024-01-17 15:46
@SpacewaIker I was able to reproduce your problem only in `nushell` (from [here](https://github.com/neovide/neovide/issues/2250#issuecomment-1892391026)) and I would say that is the culprit. `nushell` blocks the prompt until the child process terminates. Also, this is not because of `scoop` because if an application is tarted with its actual executable instead of its shim, `nushell` would wait till the process exits. I would like to hear if my commits don't work in `pwsh` or any other shell which doesn't behave this way.

**Comment by SpacewaIker** [comment] 2024-01-17 15:53
It seems that you're right, it works as expected in powershell and CMD. However it worked fine with nushell and previous versions of neovide... So now I don't know if the issue is with neovide or nushell, since it doesn't seem to come from scoop.

**Comment by spider2048** [comment] 2024-01-17 16:45
@SpacewaIker I think the issue is with `nushell` and not with `neovide` as I see a [wait](https://github.com/nushell/nushell/blob/55bf4d847fa3f2a41b746fd22b8a4355d9b1f108/crates/nu-command/src/system/run_external.rs#L486) in its code.

**Comment by Roemer** [comment] 2024-02-05 08:02
It seems that shims for GUI applications build with go/fyne-framework also open a terminal which needs to stay open. Is this also adressed with this issue?
It can be tested for example with https://github.com/Roemer/disk-tree and a following local manifest saved as `disk-tree.json`:
```json
{
    "version": "0.2.0",
    "url": "https://github.com/Roemer/disk-tree/releases/download/v0.2.0/disk-tree-0.2.0.exe",
    "bin": "disk-tree-0.2.0.exe"
}
```
and then `scoop install <path-to>/disk-tree.json`

**Comment by Roemer** [comment] 2024-02-05 15:05
Any idea when this might find its way into a release? Been a while since the last release.

**Comment by goyalyashpal** [comment] 2024-03-20 09:34
> A symbolic link doesn't work, as the exe that is the symlink's target cannot find its related .dlls, as the "exe's directory" is the directory the symlink is in, not where the target lives.
> \- @ rasa at https://github.com/ScoopInstaller/Scoop/issues/1606#issuecomment-392108771

i wonder how the wonderful <tt>[pipx]</tt> uses symlinks then? 
pipx allows to run "python packages with entry points" as standalone isolated apps.

[pipx]: https://pipx.pypa.io

following is a screenshot for the directory used by pipx to store the symlinks of the executables

<img src="https://github.com/ScoopInstaller/Scoop/assets/19423063/ba2d8008-883a-4eec-8e77-15436c3a3392" width=400px />

**Comment by pfmoore** [comment] 2024-03-20 10:14
The executables in pipx don't locate any of their resources or DLLs using paths relative to the executable, so the problem referred to doesn't arise.

**Comment by gerardog** [comment] 2024-03-20 10:20
> The executables in pipx don't locate any of their resources or DLLs using paths relative to the executable, so the problem referred to doesn't arise.

Exactly. As another example, gsudo (and possible any .net app) when built for .net framework 4.x fails to load it's .dlls if invoked from a symlink. A special workaround in code fixed that. When I later rebuilt it with .net 7 NativeAOT, the workaround was no longer needed.

**Comment by goyalyashpal** [comment] 2024-03-20 11:21
so, can this be considered as lack of convention in windows applications to resolve the paths to destination (assuming that it is possible to resolve in the first place).

as from my surfacial knowledge, in linux the executables are moved to the `bin` folder away from directory on install right away. but yeah, in there, they likely don't have to resolve their install location, but the location of system-wide `lib`s

**Comment by pfmoore** [comment] 2024-03-20 13:50
> so, can this be considered as lack of convention in windows applications to resolve the paths to destination (assuming that it is possible to resolve in the first place).

Not really. My understanding is that in Linux, shared libraries and resources are typically located in fixed absolute locations. So executables can be run from anywhere, but shared libraries and resources can't be safely moved. Conversely, in Windows the common practice is to store all application DLLs and resources in the application directory. This means you can move the application as a whole, but can't move components relative to each other.

The semantics of a symlink make it equivalent to moving the executable to another place. As the above demonstrates, this works for typical Linux applications, but doesn't work for typical Windows applications.

Applications can be written in such a way that this isn't an issue in practice (pipx shims hard-code the absolute path to the Python interpreter that gets run, but everything *else* in the app is relative to that, so you can move or symlink the shim, but not any other part of the app). But *in general* symlinking an application exe is less likely to work on Windows than Linux, because of the different conventions.

**Comment by goyalyashpal** [comment] 2024-03-20 14:14
_self hiding as resolved_

----
> in Linux, shared libraries and resources are typically located in fixed absolute locations. So executables can be run from anywhere

yeah, that was what i was thinking. thanks for the wonderful & thorough writeup :)

**Comment by 29039** [comment] 2024-03-23 07:02
For anyone playing at home who can't wait for a new release, you can access the new shim from https://github.com/ScoopInstaller/Scoop/tree/develop/supporting/shims/kiennq

**Comment by brian6932** [comment] 2024-03-24 18:00
https://github.com/ScoopInstaller/Scoop/commit/5153d7375bb932807f77f03f739a03b385ac9542 seems to break this for me
```pwsh
❯ streamlink

❯ & (scoop which streamlink)
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
```
manifests reproduced on
https://github.com/brian6932/dank-scoop/blob/master/bucket/streamlink-nightly-lean-ttv-lol.json
https://github.com/brian6932/dank-scoop/blob/master/bucket/streamlink-nightly-lean.json

**Comment by brian6932** [comment] 2024-03-24 20:15
I understand that the old shimgen can be used, but that's not really a solution, isn't the old shimgen slower anyway, the C(++) one should just be fixed.

**Comment by spider2048** [comment] 2024-03-24 20:38
How slow is the old shim? I don't really see much differences in their launch times. It's not part of my hot path, anyway.

**Closed** 2024-04-18 16:07 UTC
Labels: enhancement, help-wanted
