### ISSUE TITLE
error : fatal: failed to load library 'libcurl-4.dll'

### ISSUE THREAD

**Issue by clementin-bonneau-riera** [ScoopInstaller/Scoop#5529] opened 2023-06-04 12:02 UTC
#### Current Behavior
Issue during updating scoop apps / adding new repositories.

```
Checking repo... ERROR 'https://github.com/ScoopInstaller/Extras' doesn't look like a valid git repository

Error given:
fatal: failed to load library 'libcurl-4.dll'
```

#### Expected Behavior
Adding repositories or updating apps.

#### Additional context/output
I have tried to reinstall Scoop, after removed it and deleted scoop's folder. Nothing has changed, the same error happens.

### System details

**Windows version:** Windows 10 22H2

**OS architecture:** 64bit

**PowerShell version:** `5.1.19041.3031`

#### Scoop Configuration

```json
{
    "last_update":  "2023-06-04T13:47:56.5995998+02:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}

```

**Comment by HUMORCE** [comment] 2023-06-04 12:37
![screenshot_230604_123606](https://github.com/ScoopInstaller/Scoop/assets/4353480/3e946d16-305c-47d6-92ee-124f60330ff7)

```
scoop uninstall git
scoop install git
scoop bucket rm extras
scoop bucket add extras
```

**Comment by clementin-bonneau-riera** [comment] 2023-06-04 15:07
```
PS C:\Users\Clémentin> scoop uninstall git
Uninstalling 'git' (2.41.0.windows.1).
Removing shim 'sh.shim'.
Removing shim 'sh.exe'.
Removing shim 'bash.shim'.
Removing shim 'bash.exe'.
Removing shim 'git.shim'.
Removing shim 'git.exe'.
Removing shim 'gitk.shim'.
Removing shim 'gitk.exe'.
Removing shim 'git-gui.shim'.
Removing shim 'git-gui.exe'.
Removing shim 'scalar.shim'.
Removing shim 'scalar.exe'.
Removing shim 'tig.shim'.
Removing shim 'tig.exe'.
Removing shim 'git-bash.shim'.
Removing shim 'git-bash.exe'.
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Git Bash.lnk
Unlinking ~\scoop\apps\git\current
PS C:\Users\Clémentin> scoop install git
Installing 'git' (2.41.0.windows.1) [64bit] from main bucket
Loading PortableGit-2.41.0-64-bit.7z.exe from cache
Checking hash of PortableGit-2.41.0-64-bit.7z.exe ... ok.
Extracting dl.7z ... done.
Linking ~\scoop\apps\git\current => ~\scoop\apps\git\2.41.0.windows.1
Creating shim for 'sh'.
Creating shim for 'bash'.
Creating shim for 'git'.
Creating shim for 'gitk'.
Creating shim for 'git-gui'.
Creating shim for 'scalar'.
Creating shim for 'tig'.
Creating shim for 'git-bash'.
Creating shortcut for Git Bash (git-bash.exe)
Creating shortcut for Git GUI (git-gui.exe)
Running post_install script...
'git' (2.41.0.windows.1) was installed successfully!
Notes
-----
Set Git Credential Manager Core by running: "git config --global credential.helper manager"

To add context menu entries, run 'C:\Users\Clémentin\scoop\apps\git\current\install-context.reg'

To create file-associations for .git* and .sh files, run
'C:\Users\Clémentin\scoop\apps\git\current\install-file-associations.reg'
PS C:\Users\Clémentin> scoop bucket rm extras
ERROR 'extras' bucket not found.
PS C:\Users\Clémentin> scoop bucket add extras
Checking repo... ERROR 'https://github.com/ScoopInstaller/Extras' doesn't look like a valid git repository

Error given:
fatal: failed to load library 'libcurl-4.dll'
```
libcurl-4.dll is still missing. Where can I see the dlls, as in your screenshot?

**Comment by HUMORCE** [comment] 2023-06-04 16:42
> Where can I see the dlls, as in your screenshot?

Yes

**Comment by HUMORCE** [comment] 2023-06-06 06:21
```
Checking repo... ERROR 'https://github.com/ScoopInstaller/Extras' doesn't look like a valid git repository
```

I got this error on setup new device caused by network connection, but not contains `fatal: failed to load library 'libcurl-4.dll'`

**Comment by kunago** [comment] 2023-06-07 07:12
For some reason it starrted happening to me as well. Regular update command does not work with the same message as above and I can see the library is present.

**Comment by kunago** [comment] 2023-06-07 07:30
I am not that much into the C language, but the latest change regarding the curl library seems to be coming from this pull request: https://github.com/git-for-windows/git/pull/4410

Some culprit in the lazy loading must be messing scoop up.

To temporarily fix the issue, revert to the previous git version running ```scoop install git@2.40.1.windows.1```. It works fine afterwards.

**Comment by clementin-bonneau-riera** [comment] 2023-06-07 08:25
> To temporarily fix the issue, revert to the previous git version running scoop install git@2.40.1.windows.1. It works fine afterwards.

This worked for me, thanks !

**Comment by nikkoura** [comment] 2023-07-19 07:54
> I am not that much into the C language, but the latest change regarding the curl library seems to be coming from this pull request: [git-for-windows/git#4410](https://github.com/git-for-windows/git/pull/4410)
> 
> Some culprit in the lazy loading must be messing scoop up.
> 
> To temporarily fix the issue, revert to the previous git version running `scoop install git@2.40.1.windows.1`. It works fine afterwards.

If this specific version is not already present in your scoop installation, this will ultimately fail because of the libcurl error.
You can however switch to any other older version with:

`scoop reset  git@2.40.0.windows.1`

**Comment by whut** [comment] 2023-08-17 10:26
Directly installing from old manifest will work in all cases (only that worked for me): 


This one will install Git 2.40.1:

```shell
scoop install https://raw.githubusercontent.com/ScoopInstaller/Main/b91914ca6624244079df62b157dc57a0968e5cf7/bucket/git.json
```

**Comment by rashil2000** [comment] 2023-09-05 09:44
Closing this as an upstream issue...

**Closed by rashil2000** 2023-09-05 09:44 UTC
Labels: bug, upstream
