### ISSUE TITLE
Pollutes C:\ with junk-ish files

### ISSUE THREAD

**Issue by leaumar** [ScoopInstaller/Scoop#4415] opened 2021-07-28 12:43 UTC
I just noticed today that scoop appears to leave a lot of junk or misplace things into `C:\`:

![image](https://user-images.githubusercontent.com/3950300/127322193-e3eabc54-f085-462d-9c51-ea610d0f10ec.png)

The names that I recognize in that screenshot are some programs I've installed through scoop, and some strangers I only know as dependencies installed by scoop itself. AWS in particular was an experiment I just did: I uninstalled it and deleted the files, then ran `scoop install aws`. The result was
- the install failed with an error
- C:/Amazon created with a bunch of files inside
- C:/AWSCLIV2-2.2.23.msi created
- scoop/apps/aws created with just the same MSI and a log in there

Doing this from an admin terminal leaves none of these leftovers and creates the scoop/apps/aws folder with all the intended content. From just this one run, I conclude that some of the files in C: are left after an error. I don't know why those unfamiliar names like tcltk/test/tools/lib/doc/exe/dev are there at all.

I'm not involved with scoop besides just using it to install some dev dependencies. Should scoop have better junk file catching code? Is this a community issue, where the package maintainer for aws etc fails to set up the installation and cleanup properly?

Just wanted to bring this to attention because this seems undesirable, if not a defect. I couldn't find an existing convo or documentation on this, like a temp folder env var.

**Comment by HUMORCE** [comment] 2021-07-28 17:28
cannot reproduce.

what is the installation directory of scoop?  `$env:SCOOP`
i think it is related to files/folders permissions or environment variables.

**Comment by leaumar** [comment] 2021-07-28 20:24
Is `$env:SCOOP` a powershell command? It outputs nothing. I have no env var named SCOOP.

I followed the site's installation instructions a month or two/three ago, I would have used a user shell first and an admin shell only if it failed to install.

**Comment by HUMORCE** [comment] 2021-07-28 21:43
that's the problem, scoop cannot locate its own installation path without it.

```powershell
[environment]::setEnvironmentVariable('SCOOP','C:\Users\Marnes\scoop','User')
```

related: https://github.com/lukesampson/scoop/wiki/Quick-Start#installing-scoop-to-custom-directory

**Comment by leaumar** [comment] 2021-07-28 21:53
Shouldn't it be set up by the installation script?

**Comment by HUMORCE** [comment] 2021-07-28 22:04
yeah, `$env:SCOOP` will be set by the installation script.
maybe the environment variable is deleted by your mistake or other causes,
so set it manually or reinstall scoop again.

**Comment by leaumar** [comment] 2021-07-28 22:07
Other causes probably, I wouldn't delete it on 3 computers for no reason :) I'll see if I can reproduce a fresh install that doesn't set the var. I'll set it manually to fix it then, thanks.

**Comment by leaumar** [comment] 2021-07-28 22:10
Might I suggest adding a note to the installation doc that the env var isn't only needed for a custom directory as is implied now by it only being mentioned there, but for the default folder too?

**Comment by HUMORCE** [comment] 2021-07-28 22:16
the default installation works well. 🙄

**Comment by leaumar** [comment] 2021-07-28 22:17
Documentation isn't for when everything works ;)

**Comment by HUMORCE** [comment] 2021-07-28 22:26
I think scoop should use relative paths to avoid this problem, in the case of unspecified custom directory for itself and global apps.

**Comment by leaumar** [comment] 2021-08-04 11:46
Even with `SCOOP` set, scoop still pollutes C: sometimes. Very strange. I'm not running my terminal (the newfangled windows terminal app) as other users or admin or anything.

![image](https://user-images.githubusercontent.com/3950300/128175296-37fd37e1-2273-4b2e-b2f2-c6fe711c88ac.png)

![image](https://user-images.githubusercontent.com/3950300/128175309-19f30456-1a59-4a37-8134-e0b22ccad1ab.png)

![image](https://user-images.githubusercontent.com/3950300/128175319-e52890dc-1047-415c-abc1-c0712832c745.png)

**Comment by HUMORCE** [comment] 2021-08-04 13:42
the powershell $profile or other factors can affect the environment variables too, check environment variables in the same session.

**Comment by leaumar** [comment] 2021-08-04 13:46
Is that what `$env:SCOOP` is for? It outputs what I expect, the env var value.

**Comment by leaumar** [comment] 2021-08-04 15:48
Strangely, trying the same yarn setup on my other laptop works right away, just like with the first post in this thread. Either domain-joined (work) devices have some sort of glitch, or sophos av interferes with scoop in unwelcome ways. I can't think of any other differences between these two devices.

I guess the point of this thread is more finding out what's making scoop behave strangely rather than any systemic issue with scoop. Sorry this isn't a particularly actionable topic so far, I just gotta take the findings somewhere.

**Comment by leaumar** [comment] 2021-09-17 21:11
I just bought myself a brand new laptop a few days ago, and one of the first things I set up was scoop, using the store's windows terminal app and non-elevated ootb powershell. The env var was `SCOOP` was absolutely not set by the installer script (`iwr -useb get.scoop.sh | iex`). Only defender was running, no other software or modifications had been done yet. Can you reproduce this or do you need something more from me?

**Comment by HUMORCE** [comment] 2021-09-18 18:56
https://github.com/lukesampson/scoop/blob/092005046454d94d141d5c68fdbdb4c4a1229ae9/lib/core.ps1#L962-L977

you are right,
i install scoop in a fresh virtual machine, the install script does not set $env:SCOOP.

but these factor does not explain why the cache files were downloaded to the root of the drive, while you cannot reproduce it. 😀

**Comment by leaumar** [comment] 2021-09-18 19:08
The new laptop didn't get the pollution issue, no. I'm beginning to feel like it only happens on domain-joined PCs (my work laptop where it happened) or something, regardless of the env var.

**Comment by Cologler** [comment] 2021-09-19 00:13
What happens if you try to run scoop without load the PowerShell profile?

``` ps1
powershell -noprofile -c scoop install ...
```

**Comment by leaumar** [comment] 2021-11-04 19:42
Nothing out of the ordinary happens when I do that. It just installs correctly and doesn't leave junk.

**Comment by pratikpc** [comment] 2021-11-06 20:00
@leaumar if it works correctly on work laptop with NoProfile, can you check what's in your PowerShell Profile once?

**Comment by leaumar** [comment] 2021-11-15 13:45
From what I can tell, I don't have any. When I echo `$PROFILE`, it points to a ps1 file that doesn't exist. There are no `*profile.ps1` files in my system aside from a few that have nothing to do with my user.

**Comment by pratikpc** [comment] 2021-11-15 13:51
Can you check the content of all of these?

https://devblogs.microsoft.com/scripting/understanding-the-six-powershell-profiles/

It continues to work with powershell -NoProfile set right?

Further scoop.ps1 is located where?

You can use where.exe scoop.ps1 to find out

**Comment by leaumar** [comment] 2021-11-15 13:57
Yeah like I said, those files don't exist.

I have a `"C:\Users\leaumar\scoop\shims\scoop.ps1"` and `"C:\Users\leaumar\scoop\apps\scoop\current\bin\scoop.ps1"`

**Comment by rashil2000** [comment] 2022-01-14 18:15
You should only have `"C:\Users\leaumar\scoop\shims\scoop.ps1"` in the output. 

Closing because of lack of reproduction.

**Closed by rashil2000** 2022-01-14 18:15 UTC
Labels: question
