### ISSUE TITLE
[Bug] Cannot download normally

### ISSUE THREAD

**Issue by Vzz1c** [ScoopInstaller/Scoop#5230] opened 2022-10-29 03:37 UTC
````
{
    "proxy":  "127.0.0.1:10808",
    "default-architecture":  "64bit",
    "debug":  true,
    "last_update":  "2022-10-29T10:05:38.5007735+08:00",
    "aria2-options":  [
                          "--all-proxy=127.0.0.1:10808"
                      ],
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}
````
Download error, I do not understand why this is the case
````
https://udomain.dl.sourceforge.net/project/portableapps/Mozilla%20Thunderbird%2C%20P.E./Mozilla%20Thunderbird%2C%20Portable%20Edition%20102.4.1/ThunderbirdPortable_102.4.1_Vietnamese.paf.exe#/dl.7z
````
This url link does not seem to have any problem, but the download error (404)
In fact, I use aria2 download mode is normal, but the problem is that the automatic update check is called in the default download mode, not aria2 download mode, so the check update download hash can not be downloaded, can not update the program, this error is easy to reproduce, just use this link in the json file url download, and then directly download will appear error (scoop download xxx), but aris2 download is no problem

**Comment by HUMORCE** [comment] 2022-10-29 03:42
please attach the manifest here.

**Comment by Vzz1c** [comment] 2022-10-29 03:50
> 请在此处附上清单。



> 请在此处附上清单。

I know what the problem is,
Use irm "link" to know the normal download, and do not really use this link address

**Comment by HUMORCE** [comment] 2022-10-29 03:51
```
❯ scoop install 1ocal/tb
Installing 'tb' (1) [64bit] from 1ocal bucket
ThunderbirdPortable_102.4.1_Vietnamese.paf.exe (113.9 MB) [============================================================================================================] 100%
WARN  Warning: No hash in manifest. SHA256 for 'dl.7z' is:
    d5683bcb2c09e187f5f8ade64a7d35ee337e1075d63f4257e633acb83badd11f
Extracting dl.7z ... done.
Linking ~\scoop\apps\tb\current => ~\scoop\apps\tb\1
'tb' (1) was installed successfully!
scoop\buckets\1ocal took 21s 
❯ cat .\bucket\tb.json
{
    "version": "1",
    "url": "https://udomain.dl.sourceforge.net/project/portableapps/Mozilla%20Thunderbird%2C%20P.E./Mozilla%20Thunderbird%2C%20Portable%20Edition%20102.4.1/ThunderbirdPortable_102.4.1_Vietnamese.paf.exe#/dl.7z"
}
```

cannot reproduce.

**Comment by Vzz1c** [comment] 2022-10-29 03:53
> ```
> ❯ scoop install 1ocal/tb
> Installing 'tb' (1) [64bit] from 1ocal bucket
> ThunderbirdPortable_102.4.1_Vietnamese.paf.exe (113.9 MB) [============================================================================================================] 100%
> WARN  Warning: No hash in manifest. SHA256 for 'dl.7z' is:
>     d5683bcb2c09e187f5f8ade64a7d35ee337e1075d63f4257e633acb83badd11f
> Extracting dl.7z ... done.
> Linking ~\scoop\apps\tb\current => ~\scoop\apps\tb\1
> 'tb' (1) was installed successfully!
> scoop\buckets\1ocal took 21s 
> ❯ cat .\bucket\tb.json
> {
>     "version": "1",
>     "url": "https://udomain.dl.sourceforge.net/project/portableapps/Mozilla%20Thunderbird%2C%20P.E./Mozilla%20Thunderbird%2C%20Portable%20Edition%20102.4.1/ThunderbirdPortable_102.4.1_Vietnamese.paf.exe#/dl.7z"
> }
> ```
> 
> 无法重现。

Please try,irm Link
Is it a web page or binary data that appears?

**Comment by HUMORCE** [comment] 2022-10-29 03:57
sorry, what is **irm link**?

**Comment by Vzz1c** [comment] 2022-10-29 04:01
> 对不起，什么是**irm 链接**？

![image](https://user-images.githubusercontent.com/49944812/198812888-8dac50b5-9644-4da9-b8e7-688232bd88b6.png)

I get html data, which is normally exe binary data

**Comment by HUMORCE** [comment] 2022-10-29 04:12
```
+²10%0#+https://sectigo.com/CPSg
0DU=0;09 7 53http://crl.sectigo.com/SectigoRSATimeStampingCA.crl0t+h0f0?+03hp://cr*H÷ectigo.com/SectigoRSATimeStampingCA.crt0#+0http://ocsp.sectigo.com0
|=6 iÙó0Ú¬iÖtW$?~<ÙõÃy%l&èhÎñw9¨Ú4ÃT«ÿÄ~l+Óë´làEM,²÷;;ZµÁû×umrrö÷(óÓ²Ðë¾,xïÍE äøv»WÅ¾wTt
OMÄª¯5+Ëxéòù<Nãbë´D
uAÂ4¸È"ñjÛ/nx­Ä´ù}þh4äwå±ÎlÛm(G~.ðdûÛ¤1|û<Ñ
p¹U_G¾9dÎ·Ú#T2ãF²2ØÒ)É]¯û´Ñ.8|5àíH"jUÙòeåñ)óH       L¦yò¢¶ë(á¾}|íV¦ô"3äSü*úÀ§¨êµzÎäàK¡3«
ü½MíÉæl6þwC¸i-|a/í£°Iþ[¾i$ÿüWiKÙ?mrÓ¢ÐÀdÒ:BÁûÐí!¸?¯¦²QTÕLÅÊWÆ9í\ÿì&v­dfgèª0àÒ­·}±jA'n£tà n¿ãö·¼
h¡?nY*H÷             æ®¿`Ýõ0ì0Ô 0o¬Ýft|©F6§x-¹0
01
0       UUS10U
New Jersey10U
Jersey City10U
380118235959Z0}1Network1.0,U%USERTrust RSA Certification Authority0
0       UGB1UGreater Manchester10USalford10U
0H÷mited1%0#USectigo RSA Time Stamping CA0"0
ÈÙ,~}? ½!T¹Ï >Sï³ZÀvÖ¥ÎGµëÄÌI4ËóEe¹ù§d& ûÕ2Ry.ÉcÂ¶?fo!«ÕqyôF*ÍÄZÉÛ×]IMrVÜÉãS:*üÎXIÓ¿ó9»¹¤#B¬ÐÃ¢\×8ñ²pÓ£Äß³År¬.
O³n'uUÑ;4!{¯ÏÑ
?ÛÐêVqÑ-LÈ<Ó¢½&ÿÓS Ç`iX
ÔÄ0t!ÏbVµ!sýªXw¤ëUÿÐ9T-&îE:oÍ×ð×ð(ÅOdÔûâÞñ¼(ômÚ'ÒÞèkð[}évi J,w+ëÁxVÆD%ß-^ý¢SgÊ±úS}ú¶9X2ïoP×O3½µ¡ÞAz§£Z0V0U#0Sy¿Zª+JÏTáØÀò²fË0U¡øa ÃAwE(Ñ5_U0Uÿ0Uÿ0ÿ0U%
0
+0U 
0U 0PUI0G0E C A?http://crl.usertrust.com/USERTrustRSACertificationAuthority.crl0v+j0h0?+03http://crt.usertrust.com/USERTrustRSAAddTrustCA.crt0%+0http://ocsp.usertruscom0  *H÷
mT¥3]áµSußz2
-%²°Û*}*õ¼;'ôZ ¹IY)laËµPÛâ}ùï@Ã­ÓâäVùXAÏñBå}ÿ°tÆ\   ù3^ê &X\ó´ÕÕÃâ¼ÕXx¿HváDgm°Cäù8b¿Å£LÅÌ²S0¤Öô¸Í\¾rRj;B7|x9±Ü²mAmgÍÉo=ErÁÂUfä³ÅföóÖK^­£+B!þ¨oZ%pbsc^ »ØÜ×JÓ=¯8$-äüÖ>w¼6µçwË.#¹£ÂGð]Ö¡sWh§É7e¾ê¼ØBC¥¦    ÿÑ¡¦Nª= õl·ÒdZØ*"ÂKñ9^LÞH=4    _ý÷±RÎ?ö¡µ©uq¿[C]e=Pn«ðÐÓü²³¶&ô<y\dÌÍî'å À
rÁnMZÓêðDæ2oëNÃxe ;Aªé¡Aþ±¸ e*4àÞ¨ù<æÁ0»À c,ü\¨ÐÄêÆ¦m2]´8       +Iªýì0Úñ§/Ï·ýúÐ£Ù'ûfw¹Vá nÆ®±ù¶ºÈ5]3vñ|
*w®µ¢º)î´Z±«ãù
ÉT]Ô¹jt½H®1-0)00}1
0       UGB1UGreater Manchester10USalford10U
Sectigo1e k0*H÷Sectigo RSA Time Stamping CA9ÒJ:ò½8©C0
2102715120á=aíØÄI6õ^ÖãØ¦(ÿ*üÄ#Ù²©Z|¼©D
h2ïÜsçÿãWÎ\0í
H÷     
1Ý0Ú0×0«4:¬@ð³áøx0¼Ö[âpÁWúù#Ý­0£0¤01
0       UUS10U
New Jersey10U
Jersey City10U
:**H÷RUST Network1.0,U%USERTrust RSA Certification Authority0o¬Ýft|©F6§x-¹0
åÈLÄSx¶Çx¡?$ïHsPÏ:þÏSþ§Ä2_¥tmÕù(L¡}ëx¿9£:Ë¢ÔÕóµ ¯¡¦]ò8hÉ.=%1NvØó²6;p×íwÈÞLøÈ«¥
~®6ÖéØt-\ßÚG¤¦~ø¹ÿßÔ¼>²&üÃ}~jætÖwp¦×ó}¶½Ã´ÞÖáGËÞqA¼êHa÷lEïb 0GÒ6]Â_;æKÀ4ËÈñfb"¡z¸ãÐ$¿¦.Ó:,ëÔ¶ÑúVíwuôÅÍ¼¤m° ÜtñÓd.û²ï0ÊfµÍ
>³ç&üæ½Ûà9124z:Á3æ¾=Ù~/eîÐ^*ÿ«lbaÚMúùg%PÑùÐ
```
emmm, I get a blinking terminal window with alarm tone until to end.

for sourceforge, check here: https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#special-cases-for-fosshub-and-sourceforge

**Comment by HUMORCE** [comment] 2022-10-29 04:39
downloading the link you provided via Scoop worked fine while I tesing, so i am closing this issue for now.

**Closed by HUMORCE** 2022-10-29 04:39 UTC
Labels: bug

**Comment by Vzz1c** [comment] 2022-10-29 07:20
> 在我测试时，通过 Scoop 下载您提供的链接效果很好，所以我现在关闭这个问题。

Saya menghapus hash dari json dan sekarang berfungsi dengan baik, pembaruan otomatis tidak mengunduh dan memeriksa hash, tetapi memperbarui versi dan tautan unduhan, ada peringatan kesalahan tetapi itu sudah cukup, saya yakin itu adalah bug yang tidak terdeteksi, saya memiliki masalah pada saat yang sama di komputer lain, pada kenyataannya daftar lain di sourceforge tidak memiliki masalah ini, saya tidak tahu mengapa tautan unduhan ini sangat istimewa

**Comment by HUMORCE** [comment] 2022-10-29 07:47
https://sourceforge.net/projects/portableapps/rss?path=/Mozilla%20Thunderbird%2C%20P.E./Mozilla%20Thunderbird%2C%20Portable%20Edition%20102.4.1

```
    <item>
      <title><![CDATA[/Mozilla Thunderbird, P.E./Mozilla Thunderbird, Portable Edition 102.4.1/ThunderbirdPortable_102.4.1_English.paf.exe]]></title>
      <link>https://sourceforge.net/projects/portableapps/files/Mozilla%20Thunderbird%2C%20P.E./Mozilla%20Thunderbird%2C%20Portable%20Edition%20102.4.1/ThunderbirdPortable_102.4.1_English.paf.exe/download</link>
      <guid>https://sourceforge.net/projects/portableapps/files/Mozilla%20Thunderbird%2C%20P.E./Mozilla%20Thunderbird%2C%20Portable%20Edition%20102.4.1/ThunderbirdPortable_102.4.1_English.paf.exe/download</guid>
      <pubDate>Thu, 27 Oct 2022 16:01:15 UT</pubDate>
      <description><![CDATA[/Mozilla Thunderbird, P.E./Mozilla Thunderbird, Portable Edition 102.4.1/ThunderbirdPortable_102.4.1_English.paf.exe]]></description>
      <files:sf-file-id xmlns:files="https://sourceforge.net/api/files.rdf#">45064924</files:sf-file-id>
      <files:extra-info xmlns:files="https://sourceforge.net/api/files.rdf#">PE32 executable</files:extra-info>
      <media:content xmlns:media="http://video.search.yahoo.com/mrss/" type="application/x-dosexec; charset=binary" url="https://sourceforge.net/projects/portableapps/files/Mozilla%20Thunderbird%2C%20P.E./Mozilla%20Thunderbird%2C%20Portable%20Edition%20102.4.1/ThunderbirdPortable_102.4.1_English.paf.exe/download" filesize="119526296"><media:hash algo="md5">3c62b98ea70ce434a7f6a8b5b75f7136</media:hash></media:content>
    </item>
```

`<media:hash algo="md5">3c62b98ea70ce434a7f6a8b5b75f7136</media:hash>`

**Comment by Vzz1c** [comment] 2022-10-29 07:59
> hash

Thank you, I am not through the rss crawl, this way is too convenient, but like this particular download link using the default way can not be downloaded, only through the aria2 download is also a problem, I can not know the reason, but after such a situation, I can delete the json in the hash to solve the problem

**Comment by HUMORCE** [comment] 2022-10-29 08:58
Do you mean that the file downloaded via Scoop with a different hash value than expected in the manifest?
