### ISSUE TITLE
[Feature] Add scoop bucket priority setting functions or set the default bucket

### ISSUE THREAD

**Issue by leij0318** [ScoopInstaller/Scoop#6195] opened 2024-10-18 08:08 UTC
## Feature Request
Hello developers! I am quite satisfied with the performance of scoop on Windows, but there are still some flaws. I hope you can consider my suggestion!

I hope that scoop bucket can add the setting of installation bucket priority and replace the default bucket-main and other commands. I am a Chinese user, so I replaced the main bucket with scoop-proxy-cn (named spc-main) which is fast for Chinese users.  GitHub address: https://github.com/lzwme/scoop-proxy-cn
It would be better if spc-main could be set as the default bucket or this bucket could be used with high priority when installing apps.

**Comment by HUMORCE** [comment] 2024-10-21 02:54
Duplicate of #5131

**Closed by HUMORCE** 2024-10-21 02:54 UTC
Labels: enhancement
