### ISSUE TITLE
[Feature] Custom persist dir

### ISSUE THREAD

**Issue by rpm0372** [ScoopInstaller/Scoop#5583] opened 2023-07-18 16:04 UTC
## Feature Request
I'd like to keep my apps/shims/buckets/cache on a stripe and my persistent data on a mirror, but the 'persist' dir seems to be hardcoded as a subdir of global.

**Comment by rashil2000** [comment] 2023-10-02 09:41
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/4746

**Closed by rashil2000** 2023-10-02 09:41 UTC
Labels: enhancement
