### ISSUE TITLE
[Bug] Can't run scoop-controlled apps when username contains a space, an apostrophe, and an accented character

### ISSUE THREAD

**Issue by ericpromislow** [ScoopInstaller/Scoop#4890] opened 2022-04-27 21:53 UTC
## Bug Report

Günther O'Donoghue can't use scoop-managed apps

#### Current Behavior
```
PS C:\Users\Günther O'Donoghue> go version
Could not create process with command '"C:\Users\G?nther O'Donoghue\scoop\apps\go\current\bin\go.exe"  version'.
```
#### Expected Behavior
```
PS C:\Users\Günther O'Donoghue> go version
go version go1.17.6 windows/amd64
```

#### Additional context/output

I created another user, `Bobby O'Tables`, and can run scoop apps when logged in with that name.

I have another user waiting in the wings, named `$'` -- don't know how he/she/they will fare.

#### Possible Solution

None in mind.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1645

**Additional software:** none

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-04-21T13:28:02.8482029-07:00"
}
```

**Comment by rashil2000** [comment] 2022-04-28 02:27
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/4784

**Closed by rashil2000** 2022-04-28 02:27 UTC
Labels: bug
