### ISSUE TITLE
[Bug] Scoop search is slow

### ISSUE THREAD

**Issue by simsrw73** [ScoopInstaller/Scoop#5312] opened 2022-12-29 14:17 UTC
#### Current Behavior

scoop search is unbearably slow and has been for a while now. It used to be much faster than it is now.

There was a previous issue ([#4491](https://github.com/ScoopInstaller/Scoop/issues/4491)) that was closed without any resolution except to use a drop-in replacement. That is not a proper resolution.

#### Expected Behavior

It should be as fast as the scoop-search replacement. 

#### Additional context/output

I've cleared cache, etc. 
```
❯ scoop cache rm * && scoop cleanup * && scoop checkup
Deleted: 0 files, 0 B
Everything is shiny now!
No problems identified!
```

### System details

**Windows version:**

Windows 11 Pro v10.0.22621.0

**OS architecture:**

64bit

**PowerShell version:**

7.3.1

#### Scoop Configuration

```json
{
  "last_update": "2022-12-29T08:52:18.1347569-05:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}

```

**Comment by HUMORCE** [comment] 2022-12-29 14:54
`scoop-search.ps1`:
```
❯ scoop search msys
Results from local buckets...

Name           Version    Source   Binaries
----           -------    ------   --------
coreutils      5.97.3     main     msysmnt.exe
msys           rev13      main
msys2          2022-12-16 main
msys2          2022-12-16 nuke
gcc-msys       11.2.0-2   versions
msys2-20200517 2020-05-17 versions
openssh-msys   8.8p1-1    versions
```

`main/scoop-search`:
```
❯ scoop-search msys2
'main' bucket:
    msys2 (2022-12-16)

'nuke' bucket:
    msys2 (2022-12-16)

'versions' bucket:
    msys2-20200517 (2020-05-17)
```

`extras/sfsu`:
```
❯ sfsu search msys2
'main' bucket:
msys2 (2022-12-16)

'nuke' bucket:
msys2 (2022-12-16) [installed]

'versions' bucket:
msys2-20200517 (2020-05-17)
```

**Comment by simsrw73** [comment] 2022-12-29 15:29
```
❯ scoop info scoop-search

Name        : scoop-search
Description : Fast scoop search drop-in replacement
Version     : 1.2.0
Bucket      : main
Website     : https://github.com/shilangyu/scoop-search
License     : MIT
Updated at  : 2022-02-19 19:32:32
Updated by  : github-actions[bot]
Installed   : 1.2.0
Binaries    : scoop-search.exe
Notes       : To replace built-in scoop search, add this to $PROFILE: Invoke-Expression
              (&scoop-search --hook)
```

```
❯ time scoop-search msys
'main' bucket:
    coreutils (5.97.3) --> includes 'msysmnt.exe'
    msys (rev13)
    msys2 (2022-12-16)

'versions' bucket:
    gcc-msys (11.2.0-2)
    msys2-20200517 (2020-05-17)
    openssh-msys (8.8p1-1)

TIME: 00:00:00.0892157 <==========
```

```
❯ time scoop search msys
Results from local buckets...

Name           Version    Source   Binaries
----           -------    ------   --------
coreutils      5.97.3     main     msysmnt.exe
msys           rev13      main
msys2          2022-12-16 main
gcc-msys       11.2.0-2   versions
msys2-20200517 2020-05-17 versions
openssh-msys   8.8p1-1    versions

TIME: 00:00:10.8204684 <==========
```

**Comment by rashil2000** [comment] 2022-12-31 07:16
Duplicate of #4239

**Closed by rashil2000** 2022-12-31 07:16 UTC
Labels: bug
