### ISSUE TITLE
Aria2 and git does not support non-ASCII paths

### ISSUE THREAD

**Issue by issaclin32** [ScoopInstaller/Scoop#4629] opened 2022-01-07 07:44 UTC
Errors will occur when aria2 is enabled, and `SCOOP_DIR` contains non-ASCII chars (for example, `C:\Users\小李\scoop`). Aria2 will save the file in a **gibberish/[mojibake](https://en.wikipedia.org/wiki/Mojibake)** path such as `C:\Users\�������������\scoop`.

upstream discussion: https://github.com/aria2/aria2/issues/1417

We cannot expect **aria2** to fix this problem in a short time, but there are 2 solutions I can think of:

**(1) Ban aria2 if it is the case**
If `SCOOP_DIR` contains non-ASCII chars. Then:
Set `aria2-enabled` to false, and forbid setting it to True (also give user a message like `aria2 cannot be enabled because scoop path 'C:\Users\小李\scoop' contains non-ASCII characters`

or, **(2) Create junctions** 
If `SCOOP_DIR` contains non-ASCII chars, then:
Convert the path with **URL encode**:
`[System.Web.HttpUtility]::UrlEncode('C:\Users\小李\scoop\cache')` -> This will equal to `C%3a%5cUsers%5c%e5%b0%8f%e6%9d%8e%5cscoop%5ccache`

Create a junction `C:\users\Public\scoop-cache-C%3a%5cUsers%5c%e5%b0%8f%e6%9d%8e%5cscoop%5ccache` that points to `C:\Users\小李\scoop\cache`.

After doing this, we can set Aria2 to save the file in `C:\users\Public\scoop-cache-C%3a%5cUsers%5c%e5%b0%8f%e6%9d%8e%5cscoop%5ccache`, and it should work fine.

Asking for your opinions:
@rasa @niheaven @chawyehsu @rashil2000

**Comment by rashil2000** [comment] 2022-01-07 08:03
I'd vote for option1. I think option 2 will cause a lot of confusion for unsuspecting users. (also it's storing scoop-related stuff outside the scoop folder, so it might be thought of as 'polluting').

**Comment by niheaven** [comment] 2022-01-07 09:47
Aha, it should be native that CJK users don't let their usernames be CJK... (Display name is okay here) 🤣 

I'll check it and see if there is some more perfect solution, but now, option 1 is better.

**Comment by chawyehsu** [comment] 2022-01-07 11:20
![](https://user-images.githubusercontent.com/5764917/148536138-f74f243c-89bf-4bef-8c4a-e1df15730981.PNG)

Although aria2 logs a mojibake file path, the file was downloaded into my cache directory successfully. I can't reproduce the problem you said.

**Comment by niheaven** [comment] 2022-01-07 15:06
I found a bug that `scoop config` cannot support CJK or other Unicode characters...

**Comment by issaclin32** [comment] 2022-01-10 16:37
I tested it on a fresh install of Windows 10 21H2, and found that the problem **only happens on Powershell 5**. Powershell 7 works fine as @chawyehsu reported.

Also Scoop is complete un-usable via **cmd** in this case.
![ps52](https://user-images.githubusercontent.com/27724471/148802974-a4f80de6-376e-4321-81f6-b39f1d1b365e.jpg)

![ps72](https://user-images.githubusercontent.com/27724471/148802985-f3082d3a-6fe4-41ca-99c9-cc1aac38d2b7.jpg)

![cmd](https://user-images.githubusercontent.com/27724471/148803004-5d581846-29e0-492d-a222-cfa72bad669a.jpg)

**Comment by rashil2000** [comment] 2022-03-08 05:37
Closed in #4644

**Closed by rashil2000** 2022-03-08 05:37 UTC
Labels: bug, upstream
