### ISSUE TITLE
scoop search returns convertfrom-json : Invalid object passed in

### ISSUE THREAD

**Issue by tomasorti** [ScoopInstaller/Scoop#4202] opened 2020-12-16 21:54 UTC
Hi.
It seems similar errors have been reported, but I do not know exactly how to fix it.

```
PS C:\Users\tomas> scoop search sqlite
convertfrom-json : Invalid object passed in, ':' or '}' expected. (93): {
    "homepage": "https://github.com/JaDogg/expressPython",
    "license": "GPL-2.0-only",
<<<<<<< HEAD
    "version": "1.0.5",
    "url": "https://github.com/JaDogg/expressPython/releases/download/v1.0.5-beta/expressPython.7z",
=======
    "version": "1.0.55",
    "url": "https://github.com/JaDogg/expressPython/releases/download/v1.0.55-beta/expressPython.7z",
>>>>>>> 2159f8de0bdb636fa39c8d7200360af7915f414d
    "hash": "21b76552ff068ec602867f2cf1629d70f262cc04ce4484cd5fa7e3cf500938be",
    "bin": "expressPython.exe",
    "shortcuts": [
        [
            "expressPython.exe",
<<<<<<< HEAD
            "expressPython"
=======
            "express Python"
>>>>>>> 2159f8de0bdb636fa39c8d7200360af7915f414d
        ]
    ],
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/JaDogg/expressPython/releases/download/v$version-beta/expressPython.7z"
    }
}
At C:\Users\tomas\scoop\apps\scoop\current\lib\manifest.ps1:10 char:45
+     Get-Content $path -raw -Encoding UTF8 | convertfrom-json -ea stop
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

'dodorz' bucket:
    SQLiteExpert (5.3.5)
    Sqliteman (1.2.2)
```

Scoop is updated:

```
PS C:\Users\tomas> scoop update scoop
scoop: current (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

How shall I fix it?
Scoop rocks! 😄
Best Regards.

**Comment by Calinou** [comment] 2020-12-17 00:00
Duplicate of https://github.com/lukesampson/scoop/issues/4186, except that it's caused by another package this time.

**Comment by tomasorti** [comment] 2020-12-17 10:02
> Duplicate of #4186, except that it's caused by another package this time.

Ok, great you spotted it.😊
How do I fix it in my environment?
Thank you!

**Comment by Calinou** [comment] 2020-12-17 12:30
Search in all of your buckets for the expressPython package and fix the JSON so it's valid. You need to remove the merge conflict markers that were accidentally committed by someone.

You can find the bucket files in `%USERPROFILE\scoop`.

**Comment by tomasorti** [comment] 2020-12-20 19:37
> Search in all of your buckets for the expressPython package and fix its JSON manifest so it uses valid syntax (or remove that JSON file if you don't need it). You need to remove the merge conflict markers that were accidentally committed by someone.
> 
> You can find the bucket files in `%USERPROFILE\scoop`.

Thank you, that fixed it.

**Comment by raisercostin** [comment] 2021-05-05 17:27
I changed the `scoop\current\lib\manifest.ps1:11 char:45` file with the following try. This way you can get a warning stating at least the bad json

```
function parse_json($path) {
    if(!(test-path $path)) { return $null }
    try {
      //this was the line 45
      Get-Content $path -raw -Encoding UTF8 | convertfrom-json -ea stop
    } catch {
      warn "parsing error of $path" 
      throw
    }
}
```

Now I get something like the following:
```
λ scoop search kafka
WARN  parsing error of D:\home\raiser-apps\buckets\athrunsun\maxthon4-portable.json
convertfrom-json : Invalid JSON primitive: .
At D:\home\raiser-apps\apps\scoop\current\lib\manifest.ps1:11 char:45
+     Get-Content $path -raw -Encoding UTF8 | convertfrom-json -ea stop
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

**Closed** 2022-07-07 09:55 UTC
