### ISSUE TITLE
Scoop On Linux Via Linux PowerShell? Run apps via WINE?

### ISSUE THREAD

**Issue by davidpgil** [ScoopInstaller/Scoop#3656] opened 2019-09-21 14:50 UTC
*ducks*
...OK hear me out.

I happen to be a retro game developer who uses Linux as his daily driver OS. In retro game dev there are numerous Windows only apps such as Famitracker and FCEUX (superior Windows version) that work reliably via WINE. I know scoop requires PowerShell, but as you may know Powershell is now supported on Linux, so would Scoop work via Powershell?

I can see this being quite useful as a way to efficiently install several Windows only apps on a Linux system.

Thoughts?

**Comment by Calinou** [comment] 2019-09-21 17:08
Duplicate of #2137.

**Comment by rashil2000** [comment] 2021-10-30 13:16
Why not just simply install PowerShell on Wine?
Using Linux version of PowerShell would make no sense.

**Closed by rashil2000** 2021-10-30 13:16 UTC

**Comment by Cabbasca** [comment] 2023-03-30 18:22
why would you want to use scoop on linux when you have apt and such?

**Comment by Retia-Adolf** [comment] 2023-07-16 06:38
> why would you want to use scoop on linux when you have apt and such?

cause apt doesn't really have version management? and I don't find any other package manager auto-updates its receipts by regex matching webpages like scoop does, though it's not black magic.
