### ISSUE TITLE
[Feature] Ranking by downloads, rating

### ISSUE THREAD

**Issue by xiaoxstz** [ScoopInstaller/Scoop#5827] opened 2024-03-10 08:22 UTC
## Feature Request

Add ranking and rating functions. So, people can know which app is popular

**Comment by HUMORCE** [comment] 2024-03-10 18:04
Scoop does not statistics on users or apps (for now).

**Comment by rashil2000** [comment] 2024-04-10 18:05
Duplicate of #3781

**Closed by rashil2000** 2024-04-10 18:05 UTC
Labels: enhancement
