### ISSUE TITLE
[Bug] scoop install nvm@1.1.12: nvm not working

### ISSUE THREAD

**Issue by String10** [ScoopInstaller/Scoop#5772] opened 2023-12-27 14:50 UTC
#### Current Behavior
``` pwsh
~ ❯ scoop info nvm

Name        : nvm
Description : A node.js version management utility for Windows.
Version     : 1.1.12
Bucket      : main
Website     : https://github.com/coreybutler/nvm-windows
License     : MIT
Updated at  : 2023/11/23 04:25:23
Updated by  : github-actions[bot]
Installed   : 1.1.12
Binaries    : nvm.exe
Environment : NVM_HOME = <root>
              NVM_SYMLINK = <root>\nodejs\nodejs
Path Added  : <root>\nodejs\nodejs
Notes       : You'll need to restart powershell/cmd to have it reload Environment Variables so nvm will work correctly

~ ❯ nvm use 20.10.0
exec: "elevate.cmd": executable file not found in %PATH%:
```

#### Expected Behavior
`nvm use xx.xx.xx` runs well.

#### Additional context/output
One guy find out it's a scoop bug but but not nvm-windows.
FYI, here's [the bug in nvm-windows](https://github.com/coreybutler/nvm-windows/issues/1069).
> (what maintainer says): I'm closing this because it appears to be a problem with the Scoop installer (which we do not maintain). elevate.vbs is shipped with the installer/updater.

#### Possible Solution

recovering the missing file.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
``` pwsh
~ ❯ $($PSVersionTable.PSVersion)

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      0
```

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by HUMORCE** [comment] 2023-12-27 16:32
Duplicate of https://github.com/ScoopInstaller/Main/issues/5311

**Closed by HUMORCE** 2023-12-27 16:32 UTC
Labels: bug
