### ISSUE TITLE
[Bug] `scoop which` not searching in the proper directory

### ISSUE THREAD

**Issue by silverkorn** [ScoopInstaller/Scoop#5013] opened 2022-06-22 17:41 UTC
#### Current Behavior
Since recently, `scoop which` is not searching in the proper path. 
In this case, it's looking into `C:\Users\apps\git\current\cmd\git.exe` instead of `C:\Users\myuser\scoop\apps\git\current\cmd\git.exe`
```
> scoop which git
Convert-Path : Impossible de trouver le chemin d'accès « C:\Users\apps\git\current\cmd\git.exe », car il n'existe pas.
Au caractère C:\Users\myuser\scoop\apps\scoop\current\lib\core.ps1:653 : 23
+         $shimTarget | Convert-Path
+                       ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\apps\git\current\cmd\git.exe:String) [Convert-Path], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ConvertPathCommand

'git' not found / not a scoop shim.
```
This happens to any installed app.

#### Expected Behavior
`scoop which` should not crash and search into the current user's scoop directory.

#### Additional context/output
```
C:\Users\myuser> scoop -v
Current Scoop version:
v0.2.2 - Released at 2022-06-21

'extras' bucket:
b19ebb8c3 (HEAD -> master, origin/master, origin/HEAD) wingetui: Update to version 1.1

'java' bucket:
c8eee9be (HEAD -> master, origin/master, origin/HEAD) graalvm-nightly: Update to version 22.2.0-dev-20220617_0837

'main' bucket:
bb0a0fcd0 (HEAD -> master, origin/master, origin/HEAD) xmake: Update to version 2.6.8

'nonportable' bucket:
484b3d4 (HEAD -> master, origin/master, origin/HEAD) sql-server-management-studio-np: Update to version 15.0.18424.0
```

### System details

**Windows 10 Pro 64bit**
**PowerShell version:** 5.1, build 19041, revidion 1682

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-06-22T13:26:45.0787686-04:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master",
    "aria2-enabled":  true,
    "MSIEXTRACT_USE_LESSMSI":  true
}
```

**Comment by niheaven** [comment] 2022-06-23 10:42
It's okay here for PS7, PS5 and CMD, could not reproduce.

**Comment by silverkorn** [comment] 2022-06-30 18:09
```
Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
ANDROID_HOME                   C:\Users\myuser\scoop\apps\android-sdk\current
APPDATA                        C:\Users\myuser\AppData\Roaming
AZURE_CLI_PATH                 C:\Users\myuser\scoop\apps\azure-cli\current
AzureCLIPath                   C:\Users\myuser\scoop\apps\azure-cli\current
CMDER_ROOT                     C:\Users\myuser\scoop\apps\cmder\current
CommonProgramFiles             C:\Program Files\Common Files
CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files
CommonProgramW6432             C:\Program Files\Common Files
COMPOSER_HOME                  C:\Users\myuser\scoop\persist\composer\home
COMPUTERNAME                   LAPTOP
ComSpec                        C:\WINDOWS\system32\cmd.exe
ConEmuDir                      C:\Users\myuser\scoop\apps\cmder\current\vendor\conemu-maximus5
DriverData                     C:\Windows\System32\Drivers\DriverData
GIT_INSTALL_ROOT               C:\Users\myuser\scoop\apps\git\current
GIT_SSH                        C:\Users\myuser\scoop\apps\putty\current\plink.exe
GOROOT                         C:\Users\myuser\scoop\apps\go\current
HOMEDRIVE                      C:
HOMEPATH                       \Users\myuser
JAVA_HOME                      C:\Users\myuser\scoop\apps\temurin8-jdk\current
LOCALAPPDATA                   C:\Users\myuser\AppData\Local
LOGONSERVER                    \\NSVPWADC-01
NODE_SKIP_PLATFORM_CHECK       1
NSISDIR                        C:\Users\myuser\scoop\apps\nsis\current
NUMBER_OF_PROCESSORS           8
NVM_HOME                       C:\Users\myuser\scoop\apps\nvm\current
NVM_SYMLINK                    C:\Users\myuser\scoop\persist\nvm\nodejs\nodejs
OneDrive                       C:\Users\myuser\OneDrive
OnlineServices                 Online Services
OS                             Windows_NT
Path                           C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDO...
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PHP_INI_SCAN_DIR               C:\Users\myuser\scoop\apps\php\current\cli;C:\Users\myuser\scoop\apps\php\current\cli...
platformcode                   AN
PROCESSOR_ARCHITECTURE         AMD64
PROCESSOR_IDENTIFIER           Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
PROCESSOR_LEVEL                6
PROCESSOR_REVISION             8e0c
ProgramData                    C:\ProgramData
ProgramFiles                   C:\Program Files
ProgramFiles(x86)              C:\Program Files (x86)
ProgramW6432                   C:\Program Files
PROGUARD_HOME                  C:\Users\myuser\scoop\apps\android-sdk\current\tools\proguard
PROJECTS_PATH                  C:\Users\myuser\Workspace\Git
PROMPT                         $P$G
PSModulePath                   C:\Users\myuser\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShel...
PTSMINSTALLPATH                c:\Program Files\HP\HP ProtectTools Security Manager\Bin\
PTSMINSTALLPATH_X86            C:\Program Files (x86)\HP\HP ProtectTools Security Manager\Bin\
PUBLIC                         C:\Users\Public
RegionCode                     LA
SCOOP                          C:\Users\myuser\scoop
SESSIONNAME                    Console
SystemDrive                    C:
SystemRoot                     C:\WINDOWS
TEMP                           C:\Users\myuser\AppData\Local\Temp
TMP                            C:\Users\myuser\AppData\Local\Temp
USERDNSDOMAIN                  CORP.NETWORK
USERDOMAIN                     CORP
USERDOMAIN_ROAMINGPROFILE      CORP
USERNAME                       myuser
USERPROFILE                    C:\Users\myuser
VBOX_MSI_INSTALL_PATH          C:\Users\myuser\scoop\apps\virtualbox-np\6.1.22\
windir                         C:\WINDOWS
ZES_ENABLE_SYSMAN              1
```

Do you know which configuration or environment variable(s) is used to generate the `which` path?

**Comment by rashil2000** [comment] 2022-07-01 06:36
The SCOOP variable is pointing to its default location in your environment. Can you delete it and try again?

**Comment by silverkorn** [comment] 2022-07-08 21:15
Unfortunately, no.
I tried by removing it and also by re-adding it as both user and system environment variables then restart the command prompt to refresh the environment variable but it still happens...

```
C:\Users\myuser>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.

Testez le nouveau système multiplateforme PowerShell https://aka.ms/pscore6

PS C:\Users\myuser> gci env:

Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
ANDROID_HOME                   C:\Users\myuser\scoop\apps\android-sdk\current
APPDATA                        C:\Users\myuser\AppData\Roaming
AZURE_CLI_PATH                 C:\Users\myuser\scoop\apps\azure-cli\current
AzureCLIPath                   C:\Users\myuser\scoop\apps\azure-cli\current
CMDER_ROOT                     C:\Users\myuser\scoop\apps\cmder\current
CommonProgramFiles             C:\Program Files\Common Files
CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files
CommonProgramW6432             C:\Program Files\Common Files
COMPOSER_HOME                  C:\Users\myuser\scoop\persist\composer\home
COMPUTERNAME                   LAPTOP
ComSpec                        C:\WINDOWS\system32\cmd.exe
ConEmuDir                      C:\Users\myuser\scoop\apps\cmder\current\vendor\conemu-maximus5
DriverData                     C:\Windows\System32\Drivers\DriverData
GIT_INSTALL_ROOT               C:\Users\myuser\scoop\apps\git\current
GIT_SSH                        C:\Users\myuser\scoop\apps\putty\current\plink.exe
GOROOT                         C:\Users\myuser\scoop\apps\go\current
HOMEDRIVE                      C:
HOMEPATH                       \Users\myuser
JAVA_HOME                      C:\Users\myuser\scoop\apps\temurin8-jdk\current
LOCALAPPDATA                   C:\Users\myuser\AppData\Local
LOGONSERVER                    \\NSVPWADC-01
NODE_SKIP_PLATFORM_CHECK       1
NSISDIR                        C:\Users\myuser\scoop\apps\nsis\current
NUMBER_OF_PROCESSORS           8
NVM_HOME                       C:\Users\myuser\scoop\apps\nvm\current
NVM_SYMLINK                    C:\Users\myuser\scoop\persist\nvm\nodejs\nodejs
OneDrive                       C:\Users\myuser\OneDrive
OnlineServices                 Online Services
OS                             Windows_NT
Path                           C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDO...
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PHP_INI_SCAN_DIR               C:\Users\myuser\scoop\apps\php\current\cli;C:\Users\myuser\scoop\apps\php\current\cli...
platformcode                   AN
PROCESSOR_ARCHITECTURE         AMD64
PROCESSOR_IDENTIFIER           Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
PROCESSOR_LEVEL                6
PROCESSOR_REVISION             8e0c
ProgramData                    C:\ProgramData
ProgramFiles                   C:\Program Files
ProgramFiles(x86)              C:\Program Files (x86)
ProgramW6432                   C:\Program Files
PROGUARD_HOME                  C:\Users\myuser\scoop\apps\android-sdk\current\tools\proguard
PROJECTS_PATH                  C:\Users\myuser\Workspace\Git
PROMPT                         $P$G
PSModulePath                   C:\Users\myuser\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShel...
PTSMINSTALLPATH                c:\Program Files\HP\HP ProtectTools Security Manager\Bin\
PTSMINSTALLPATH_X86            C:\Program Files (x86)\HP\HP ProtectTools Security Manager\Bin\
PUBLIC                         C:\Users\Public
RegionCode                     LA
SESSIONNAME                    Console
SystemDrive                    C:
SystemRoot                     C:\WINDOWS
TEMP                           C:\Users\myuser\AppData\Local\Temp
TMP                            C:\Users\myuser\AppData\Local\Temp
USERDNSDOMAIN                  CORP.NETWORK
USERDOMAIN                     CORP
USERDOMAIN_ROAMINGPROFILE      CORP
USERNAME                       myuser
USERPROFILE                    C:\Users\myuser
VBOX_MSI_INSTALL_PATH          C:\Users\myuser\scoop\apps\virtualbox-np\6.1.22\
windir                         C:\WINDOWS
ZES_ENABLE_SYSMAN              1



PS C:\Users\myuser> scoop which git
Convert-Path : Impossible de trouver le chemin d'accès « C:\Users\apps\git\current\cmd\git.exe », car il n'existe pas.
Au caractère C:\Users\myuser\scoop\apps\scoop\current\lib\core.ps1:653 : 23
+         $shimTarget | Convert-Path
+                       ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\apps\git\current\cmd\git.exe:String) [Convert-Path], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ConvertPathCommand

'git' not found / not a scoop shim.

PS C:\Users\danboi> exit



C:\Users\myuser>scoop which git
Convert-Path : Impossible de trouver le chemin d'accès « C:\Users\apps\git\current\cmd\git.exe », car il n'existe pas.
Au caractère C:\Users\myuser\scoop\apps\scoop\current\lib\core.ps1:653 : 23
+         $shimTarget | Convert-Path
+                       ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\apps\git\current\cmd\git.exe:String) [Convert-Path], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ConvertPathCommand

'git' not found / not a scoop shim.

```

Do you have little hints on where this path is built in the core for the `which` command? 
I could try to give a little test and debug there.

**Comment by rashil2000** [comment] 2022-07-10 06:44
`scoop-which` uses the `Get-CommandPath` function, which can be found here: https://github.com/ScoopInstaller/Scoop/blob/80b52e32a11fda2089949aaec00295d6185da3f7/lib/core.ps1#L329-L360 

`Get-CommandPath` in turn uses `Get-ShimTarget` function, which seems to be the source of error, found here: https://github.com/ScoopInstaller/Scoop/blob/80b52e32a11fda2089949aaec00295d6185da3f7/lib/core.ps1#L643-L655

**Comment by slaughtering** [comment] 2022-07-15 10:38
same bug with  Env:\SCOOP set to c:\scoop

**Comment by rashil2000** [comment] 2022-07-29 05:21
@silverkorn were you able to find anything?

**Comment by silverkorn** [comment] 2022-08-02 00:13
Not exactly but I've realized that it happens on my office's laptop. Same for you new colleague.
Trying on our personal machine works though...
So something might be blocked or altered by some GPO or similar event during the scripts' execution.

I'll get back to you if I have a chance to look back into it.
Thanks!

**Comment by silverkorn** [comment] 2022-08-15 15:22
Ok, so for all affected applications having this issue, I needed to uninstall and re-install it **twice**.

Whenever there's this error during uninstallation: 
```
> scoop uninstall app
ERROR 'app' isn't installed correctly.
Removing older version (x.x.x).
'app' was uninstalled.
```

I needed to install, uninstall and install a second time:
```
> scoop install app
> scoop uninstall app
> scoop install app
```

Then the `scoop which app` works.

Not sure it could be fixed in a future release, but it would be convenient to avoid doing this or maybe at least letting the user know about these steps if something is not working properly with their application even after a single reinstallation.

**Comment by rashil2000** [comment] 2022-08-15 17:18
Did you try the `scoop reset app` command? It should recreate problematic shims, if any.

**Comment by silverkorn** [comment] 2022-08-15 20:41
Just tried it with a problematic application (`sourcetree` in this case) and I see there's an `installation failed` info with `scoop list`, and doing `scoop reset sourcetree` didn't work:
```
> scoop list
Name               Version                 Source           Updated             Info
----               -------                 ------           -------             ----
[...]
sourcetree                                                  2021-07-02 14:07:44 Install failed
[...]


> scoop reset sourcetree
ERROR 'sourcetree' isn't installed


> scoop which sourcetree
Convert-Path : Impossible de trouver le chemin d'accès «C:\Users\apps\sourcetree\current\sourcetree.exe», car il
n'existe pas.
Au caractère C:\Users\danboi\scoop\apps\scoop\current\lib\core.ps1:682 : 23
+         $shimTarget | Convert-Path
+                       ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\apps\s...\sourcetree.exe:String) [Convert-Path], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ConvertPathCommand

'sourcetree' not found / not a scoop shim.
```

But launching the application & using the Window's `where` command works because it's executable is found in the shim directory:
```
> where sourcetree
C:\Users\danboi\scoop\shims\sourcetree.exe
```

---

Unfortunately this is not what I need. I'm looking for the path of the original executable.

**Comment by rashil2000** [comment] 2022-08-16 06:41
What is the content of C:\Users\danboi\scoop\shims\sourcetree.shim file?

**Comment by silverkorn** [comment] 2022-08-16 21:37
```
> type C:\Users\danboi\scoop\shims\sourcetree.shim
 ﻿path = C:\Users\danboi\scoop\apps\sourcetree\current\sourcetree.exe
```

But if I try a new one I've reinstalled twice and now works, I see quotes for the path:
```
> type C:\Users\danboi\scoop\shims\git-bash.shim
path = "C:\Users\danboi\scoop\apps\git\current\git-bash.exe"
```

I tried to add quotes on my own in the `C:\Users\danboi\scoop\shims\sourcetree.shim` file but without success...

One notice though, there's a space at the beginning when I `type` a problematic shim file, even if I've managed to clear anything there in a text editor and saving back...
Turns out it was because it was saved as `UTF-8 BOM` instead of `UTF-8`. 
But again, saving it to the same format as a working one still has problem with both `scoop which app` & `scoop reset app`

**Comment by rashil2000** [comment] 2022-08-17 05:51
All new shims have the double quoted path as you noted. But if the problem is there even after quoting, can you try to narrow down the problematic code part from the functions I referenced above? You can put debug statements and check the return value of each function.

Before that, ensure Scoop is updated to the latest version.

**Comment by rashil2000** [comment] 2023-01-07 10:20
Closing due to no feedback...

**Closed by rashil2000** 2023-01-07 10:20 UTC
Labels: bug
